// Auto-generated. Do not edit by hand.
#ifndef LUCIDE_ICONS_H
#define LUCIDE_ICONS_H

#include <stdint.h>

#define ICON_MIN_LUCIDE 0xE038
#define ICON_MAX_LUCIDE 0xE6CF

// ImGui glyph ranges (use with AddFontFromFileTTF(..., ranges))
// Example:
//   ImFontConfig cfg; cfg.MergeMode = true;
//   io.Fonts->AddFontFromFileTTF("lucide.ttf", size, &cfg, ICON_LUCIDE_RANGES);

#ifdef __cplusplus
#include "imgui.h"
static const ImWchar ICON_LUCIDE_RANGES[] = {
    0xE038, 0xE6CF,
    0
};
#endif

#define ICON_LUCIDE_A_ARROW_DOWN "\xee\x96\x85"  // U+E585
#define ICON_LUCIDE_A_ARROW_UP "\xee\x96\x86"  // U+E586
#define ICON_LUCIDE_A_LARGE_SMALL "\xee\x96\x87"  // U+E587
#define ICON_LUCIDE_ACCESSIBILITY "\xee\x8a\x97"  // U+E297
#define ICON_LUCIDE_ACTIVITY "\xee\x80\xb8"  // U+E038
#define ICON_LUCIDE_AIR_VENT "\xee\x8d\x8d"  // U+E34D
#define ICON_LUCIDE_AIRPLAY "\xee\x80\xb9"  // U+E039
#define ICON_LUCIDE_ALARM_CLOCK "\xee\x80\xba"  // U+E03A
#define ICON_LUCIDE_ALARM_CLOCK_CHECK "\xee\x87\xac"  // U+E1EC
#define ICON_LUCIDE_ALARM_CLOCK_MINUS "\xee\x87\xad"  // U+E1ED
#define ICON_LUCIDE_ALARM_CLOCK_OFF "\xee\x88\xbb"  // U+E23B
#define ICON_LUCIDE_ALARM_CLOCK_PLUS "\xee\x87\xae"  // U+E1EE
#define ICON_LUCIDE_ALARM_SMOKE "\xee\x95\xbb"  // U+E57B
#define ICON_LUCIDE_ALBUM "\xee\x80\xbb"  // U+E03B
#define ICON_LUCIDE_ALIGN_CENTER_HORIZONTAL "\xee\x89\xac"  // U+E26C
#define ICON_LUCIDE_ALIGN_CENTER_VERTICAL "\xee\x89\xad"  // U+E26D
#define ICON_LUCIDE_ALIGN_END_HORIZONTAL "\xee\x89\xae"  // U+E26E
#define ICON_LUCIDE_ALIGN_END_VERTICAL "\xee\x89\xaf"  // U+E26F
#define ICON_LUCIDE_ALIGN_HORIZONTAL_DISTRIBUTE_CENTER "\xee\x80\xbc"  // U+E03C
#define ICON_LUCIDE_ALIGN_HORIZONTAL_DISTRIBUTE_END "\xee\x80\xbd"  // U+E03D
#define ICON_LUCIDE_ALIGN_HORIZONTAL_DISTRIBUTE_START "\xee\x80\xbe"  // U+E03E
#define ICON_LUCIDE_ALIGN_HORIZONTAL_JUSTIFY_CENTER "\xee\x89\xb2"  // U+E272
#define ICON_LUCIDE_ALIGN_HORIZONTAL_JUSTIFY_END "\xee\x89\xb3"  // U+E273
#define ICON_LUCIDE_ALIGN_HORIZONTAL_JUSTIFY_START "\xee\x89\xb4"  // U+E274
#define ICON_LUCIDE_ALIGN_HORIZONTAL_SPACE_AROUND "\xee\x89\xb5"  // U+E275
#define ICON_LUCIDE_ALIGN_HORIZONTAL_SPACE_BETWEEN "\xee\x89\xb6"  // U+E276
#define ICON_LUCIDE_ALIGN_START_HORIZONTAL "\xee\x89\xb0"  // U+E270
#define ICON_LUCIDE_ALIGN_START_VERTICAL "\xee\x89\xb1"  // U+E271
#define ICON_LUCIDE_ALIGN_VERTICAL_DISTRIBUTE_CENTER "\xee\x89\xbe"  // U+E27E
#define ICON_LUCIDE_ALIGN_VERTICAL_DISTRIBUTE_END "\xee\x89\xbf"  // U+E27F
#define ICON_LUCIDE_ALIGN_VERTICAL_DISTRIBUTE_START "\xee\x8a\x80"  // U+E280
#define ICON_LUCIDE_ALIGN_VERTICAL_JUSTIFY_CENTER "\xee\x89\xb7"  // U+E277
#define ICON_LUCIDE_ALIGN_VERTICAL_JUSTIFY_END "\xee\x89\xb8"  // U+E278
#define ICON_LUCIDE_ALIGN_VERTICAL_JUSTIFY_START "\xee\x89\xb9"  // U+E279
#define ICON_LUCIDE_ALIGN_VERTICAL_SPACE_AROUND "\xee\x89\xba"  // U+E27A
#define ICON_LUCIDE_ALIGN_VERTICAL_SPACE_BETWEEN "\xee\x89\xbb"  // U+E27B
#define ICON_LUCIDE_AMBULANCE "\xee\x96\xbb"  // U+E5BB
#define ICON_LUCIDE_AMPERSAND "\xee\x92\x9c"  // U+E49C
#define ICON_LUCIDE_AMPERSANDS "\xee\x92\x9d"  // U+E49D
#define ICON_LUCIDE_AMPHORA "\xee\x98\x9b"  // U+E61B
#define ICON_LUCIDE_ANCHOR "\xee\x80\xbf"  // U+E03F
#define ICON_LUCIDE_ANGRY "\xee\x8b\xbc"  // U+E2FC
#define ICON_LUCIDE_ANNOYED "\xee\x8b\xbd"  // U+E2FD
#define ICON_LUCIDE_ANTENNA "\xee\x93\xa2"  // U+E4E2
#define ICON_LUCIDE_ANVIL "\xee\x96\x80"  // U+E580
#define ICON_LUCIDE_APERTURE "\xee\x81\x80"  // U+E040
#define ICON_LUCIDE_APP_WINDOW "\xee\x90\xa6"  // U+E426
#define ICON_LUCIDE_APP_WINDOW_MAC "\xee\x97\x92"  // U+E5D2
#define ICON_LUCIDE_APPLE "\xee\x8d\x8e"  // U+E34E
#define ICON_LUCIDE_ARCHIVE "\xee\x81\x81"  // U+E041
#define ICON_LUCIDE_ARCHIVE_RESTORE "\xee\x8b\x8d"  // U+E2CD
#define ICON_LUCIDE_ARCHIVE_X "\xee\x94\x8c"  // U+E50C
#define ICON_LUCIDE_ARMCHAIR "\xee\x8b\x80"  // U+E2C0
#define ICON_LUCIDE_ARROW_BIG_DOWN "\xee\x87\xa1"  // U+E1E1
#define ICON_LUCIDE_ARROW_BIG_DOWN_DASH "\xee\x90\x9d"  // U+E41D
#define ICON_LUCIDE_ARROW_BIG_LEFT "\xee\x87\xa2"  // U+E1E2
#define ICON_LUCIDE_ARROW_BIG_LEFT_DASH "\xee\x90\x9e"  // U+E41E
#define ICON_LUCIDE_ARROW_BIG_RIGHT "\xee\x87\xa3"  // U+E1E3
#define ICON_LUCIDE_ARROW_BIG_RIGHT_DASH "\xee\x90\x9f"  // U+E41F
#define ICON_LUCIDE_ARROW_BIG_UP "\xee\x87\xa4"  // U+E1E4
#define ICON_LUCIDE_ARROW_BIG_UP_DASH "\xee\x90\xa0"  // U+E420
#define ICON_LUCIDE_ARROW_DOWN "\xee\x81\x82"  // U+E042
#define ICON_LUCIDE_ARROW_DOWN_0_1 "\xee\x90\x93"  // U+E413
#define ICON_LUCIDE_ARROW_DOWN_1_0 "\xee\x90\x94"  // U+E414
#define ICON_LUCIDE_ARROW_DOWN_A_Z "\xee\x90\x95"  // U+E415
#define ICON_LUCIDE_ARROW_DOWN_FROM_LINE "\xee\x91\x94"  // U+E454
#define ICON_LUCIDE_ARROW_DOWN_LEFT "\xee\x81\x83"  // U+E043
#define ICON_LUCIDE_ARROW_DOWN_NARROW_WIDE "\xee\x81\x84"  // U+E044
#define ICON_LUCIDE_ARROW_DOWN_RIGHT "\xee\x81\x85"  // U+E045
#define ICON_LUCIDE_ARROW_DOWN_TO_DOT "\xee\x91\x8d"  // U+E44D
#define ICON_LUCIDE_ARROW_DOWN_TO_LINE "\xee\x91\x95"  // U+E455
#define ICON_LUCIDE_ARROW_DOWN_UP "\xee\x81\x86"  // U+E046
#define ICON_LUCIDE_ARROW_DOWN_WIDE_NARROW "\xee\x81\x87"  // U+E047
#define ICON_LUCIDE_ARROW_DOWN_Z_A "\xee\x90\x96"  // U+E416
#define ICON_LUCIDE_ARROW_LEFT "\xee\x81\x88"  // U+E048
#define ICON_LUCIDE_ARROW_LEFT_FROM_LINE "\xee\x91\x96"  // U+E456
#define ICON_LUCIDE_ARROW_LEFT_RIGHT "\xee\x89\x8a"  // U+E24A
#define ICON_LUCIDE_ARROW_LEFT_TO_LINE "\xee\x91\x97"  // U+E457
#define ICON_LUCIDE_ARROW_RIGHT "\xee\x81\x89"  // U+E049
#define ICON_LUCIDE_ARROW_RIGHT_FROM_LINE "\xee\x91\x98"  // U+E458
#define ICON_LUCIDE_ARROW_RIGHT_LEFT "\xee\x90\x97"  // U+E417
#define ICON_LUCIDE_ARROW_RIGHT_TO_LINE "\xee\x91\x99"  // U+E459
#define ICON_LUCIDE_ARROW_UP "\xee\x81\x8a"  // U+E04A
#define ICON_LUCIDE_ARROW_UP_0_1 "\xee\x90\x98"  // U+E418
#define ICON_LUCIDE_ARROW_UP_1_0 "\xee\x90\x99"  // U+E419
#define ICON_LUCIDE_ARROW_UP_A_Z "\xee\x90\x9a"  // U+E41A
#define ICON_LUCIDE_ARROW_UP_DOWN "\xee\x8d\xbd"  // U+E37D
#define ICON_LUCIDE_ARROW_UP_FROM_DOT "\xee\x91\x8e"  // U+E44E
#define ICON_LUCIDE_ARROW_UP_FROM_LINE "\xee\x91\x9a"  // U+E45A
#define ICON_LUCIDE_ARROW_UP_LEFT "\xee\x81\x8b"  // U+E04B
#define ICON_LUCIDE_ARROW_UP_NARROW_WIDE "\xee\x81\x8c"  // U+E04C
#define ICON_LUCIDE_ARROW_UP_RIGHT "\xee\x81\x8d"  // U+E04D
#define ICON_LUCIDE_ARROW_UP_TO_LINE "\xee\x91\x9b"  // U+E45B
#define ICON_LUCIDE_ARROW_UP_WIDE_NARROW "\xee\x90\x9b"  // U+E41B
#define ICON_LUCIDE_ARROW_UP_Z_A "\xee\x90\x9c"  // U+E41C
#define ICON_LUCIDE_ARROWS_UP_FROM_LINE "\xee\x93\x94"  // U+E4D4
#define ICON_LUCIDE_ASTERISK "\xee\x87\xaf"  // U+E1EF
#define ICON_LUCIDE_AT_SIGN "\xee\x81\x8e"  // U+E04E
#define ICON_LUCIDE_ATOM "\xee\x8f\x97"  // U+E3D7
#define ICON_LUCIDE_AUDIO_LINES "\xee\x95\x9a"  // U+E55A
#define ICON_LUCIDE_AUDIO_WAVEFORM "\xee\x95\x9b"  // U+E55B
#define ICON_LUCIDE_AWARD "\xee\x81\x8f"  // U+E04F
#define ICON_LUCIDE_AXE "\xee\x81\x90"  // U+E050
#define ICON_LUCIDE_AXIS_3D "\xee\x8b\xbe"  // U+E2FE
#define ICON_LUCIDE_BABY "\xee\x8b\x8e"  // U+E2CE
#define ICON_LUCIDE_BACKPACK "\xee\x8b\x88"  // U+E2C8
#define ICON_LUCIDE_BADGE "\xee\x91\xb4"  // U+E474
#define ICON_LUCIDE_BADGE_ALERT "\xee\x91\xb5"  // U+E475
#define ICON_LUCIDE_BADGE_CENT "\xee\x94\x8f"  // U+E50F
#define ICON_LUCIDE_BADGE_CHECK "\xee\x89\x81"  // U+E241
#define ICON_LUCIDE_BADGE_DOLLAR_SIGN "\xee\x91\xb6"  // U+E476
#define ICON_LUCIDE_BADGE_EURO "\xee\x94\x90"  // U+E510
#define ICON_LUCIDE_BADGE_INDIAN_RUPEE "\xee\x94\x91"  // U+E511
#define ICON_LUCIDE_BADGE_INFO "\xee\x91\xb7"  // U+E477
#define ICON_LUCIDE_BADGE_JAPANESE_YEN "\xee\x94\x92"  // U+E512
#define ICON_LUCIDE_BADGE_MINUS "\xee\x91\xb8"  // U+E478
#define ICON_LUCIDE_BADGE_PERCENT "\xee\x91\xb9"  // U+E479
#define ICON_LUCIDE_BADGE_PLUS "\xee\x91\xba"  // U+E47A
#define ICON_LUCIDE_BADGE_POUND_STERLING "\xee\x94\x93"  // U+E513
#define ICON_LUCIDE_BADGE_QUESTION_MARK "\xee\x91\xbb"  // U+E47B
#define ICON_LUCIDE_BADGE_RUSSIAN_RUBLE "\xee\x94\x94"  // U+E514
#define ICON_LUCIDE_BADGE_SWISS_FRANC "\xee\x94\x95"  // U+E515
#define ICON_LUCIDE_BADGE_TURKISH_LIRA "\xee\x99\xbe"  // U+E67E
#define ICON_LUCIDE_BADGE_X "\xee\x91\xbc"  // U+E47C
#define ICON_LUCIDE_BAGGAGE_CLAIM "\xee\x8b\x89"  // U+E2C9
#define ICON_LUCIDE_BALLOON "\xee\x9a\xaf"  // U+E6AF
#define ICON_LUCIDE_BAN "\xee\x81\x91"  // U+E051
#define ICON_LUCIDE_BANANA "\xee\x8d\x8f"  // U+E34F
#define ICON_LUCIDE_BANDAGE "\xee\x98\x9d"  // U+E61D
#define ICON_LUCIDE_BANKNOTE "\xee\x81\x92"  // U+E052
#define ICON_LUCIDE_BANKNOTE_ARROW_DOWN "\xee\x99\x8c"  // U+E64C
#define ICON_LUCIDE_BANKNOTE_ARROW_UP "\xee\x99\x8d"  // U+E64D
#define ICON_LUCIDE_BANKNOTE_X "\xee\x99\x8e"  // U+E64E
#define ICON_LUCIDE_BARCODE "\xee\x94\xb3"  // U+E533
#define ICON_LUCIDE_BARREL "\xee\x99\xb5"  // U+E675
#define ICON_LUCIDE_BASELINE "\xee\x8a\x85"  // U+E285
#define ICON_LUCIDE_BATH "\xee\x8a\xab"  // U+E2AB
#define ICON_LUCIDE_BATTERY "\xee\x81\x93"  // U+E053
#define ICON_LUCIDE_BATTERY_CHARGING "\xee\x81\x94"  // U+E054
#define ICON_LUCIDE_BATTERY_FULL "\xee\x81\x95"  // U+E055
#define ICON_LUCIDE_BATTERY_LOW "\xee\x81\x96"  // U+E056
#define ICON_LUCIDE_BATTERY_MEDIUM "\xee\x81\x97"  // U+E057
#define ICON_LUCIDE_BATTERY_PLUS "\xee\x98\xbe"  // U+E63E
#define ICON_LUCIDE_BATTERY_WARNING "\xee\x8e\xac"  // U+E3AC
#define ICON_LUCIDE_BEAKER "\xee\x81\x98"  // U+E058
#define ICON_LUCIDE_BEAN "\xee\x8e\x8f"  // U+E38F
#define ICON_LUCIDE_BEAN_OFF "\xee\x8e\x90"  // U+E390
#define ICON_LUCIDE_BED "\xee\x8b\x81"  // U+E2C1
#define ICON_LUCIDE_BED_DOUBLE "\xee\x8b\x82"  // U+E2C2
#define ICON_LUCIDE_BED_SINGLE "\xee\x8b\x83"  // U+E2C3
#define ICON_LUCIDE_BEEF "\xee\x8e\xa5"  // U+E3A5
#define ICON_LUCIDE_BEER "\xee\x8b\x8f"  // U+E2CF
#define ICON_LUCIDE_BEER_OFF "\xee\x97\x99"  // U+E5D9
#define ICON_LUCIDE_BELL "\xee\x81\x99"  // U+E059
#define ICON_LUCIDE_BELL_DOT "\xee\x90\xab"  // U+E42B
#define ICON_LUCIDE_BELL_ELECTRIC "\xee\x95\xbc"  // U+E57C
#define ICON_LUCIDE_BELL_MINUS "\xee\x87\xb0"  // U+E1F0
#define ICON_LUCIDE_BELL_OFF "\xee\x81\x9a"  // U+E05A
#define ICON_LUCIDE_BELL_PLUS "\xee\x87\xb1"  // U+E1F1
#define ICON_LUCIDE_BELL_RING "\xee\x88\xa4"  // U+E224
#define ICON_LUCIDE_BETWEEN_HORIZONTAL_END "\xee\x96\x91"  // U+E591
#define ICON_LUCIDE_BETWEEN_HORIZONTAL_START "\xee\x96\x92"  // U+E592
#define ICON_LUCIDE_BETWEEN_VERTICAL_END "\xee\x96\x93"  // U+E593
#define ICON_LUCIDE_BETWEEN_VERTICAL_START "\xee\x96\x94"  // U+E594
#define ICON_LUCIDE_BICEPS_FLEXED "\xee\x97\xab"  // U+E5EB
#define ICON_LUCIDE_BIKE "\xee\x87\x92"  // U+E1D2
#define ICON_LUCIDE_BINARY "\xee\x87\xb2"  // U+E1F2
#define ICON_LUCIDE_BINOCULARS "\xee\x98\xa1"  // U+E621
#define ICON_LUCIDE_BIOHAZARD "\xee\x91\x81"  // U+E441
#define ICON_LUCIDE_BIRD "\xee\x8f\x85"  // U+E3C5
#define ICON_LUCIDE_BIRDHOUSE "\xee\x9a\x9a"  // U+E69A
#define ICON_LUCIDE_BITCOIN "\xee\x81\x9b"  // U+E05B
#define ICON_LUCIDE_BLEND "\xee\x96\x9c"  // U+E59C
#define ICON_LUCIDE_BLINDS "\xee\x8f\x80"  // U+E3C0
#define ICON_LUCIDE_BLOCKS "\xee\x93\xba"  // U+E4FA
#define ICON_LUCIDE_BLUETOOTH "\xee\x81\x9c"  // U+E05C
#define ICON_LUCIDE_BLUETOOTH_CONNECTED "\xee\x86\xb8"  // U+E1B8
#define ICON_LUCIDE_BLUETOOTH_OFF "\xee\x86\xb9"  // U+E1B9
#define ICON_LUCIDE_BLUETOOTH_SEARCHING "\xee\x86\xba"  // U+E1BA
#define ICON_LUCIDE_BOLD "\xee\x81\x9d"  // U+E05D
#define ICON_LUCIDE_BOLT "\xee\x96\x8c"  // U+E58C
#define ICON_LUCIDE_BOMB "\xee\x8b\xbf"  // U+E2FF
#define ICON_LUCIDE_BONE "\xee\x8d\x98"  // U+E358
#define ICON_LUCIDE_BOOK "\xee\x81\x9e"  // U+E05E
#define ICON_LUCIDE_BOOK_A "\xee\x95\x84"  // U+E544
#define ICON_LUCIDE_BOOK_ALERT "\xee\x99\xb2"  // U+E672
#define ICON_LUCIDE_BOOK_AUDIO "\xee\x95\x85"  // U+E545
#define ICON_LUCIDE_BOOK_CHECK "\xee\x95\x86"  // U+E546
#define ICON_LUCIDE_BOOK_COPY "\xee\x8f\xac"  // U+E3EC
#define ICON_LUCIDE_BOOK_DASHED "\xee\x8f\xad"  // U+E3ED
#define ICON_LUCIDE_BOOK_DOWN "\xee\x8f\xae"  // U+E3EE
#define ICON_LUCIDE_BOOK_HEADPHONES "\xee\x95\x87"  // U+E547
#define ICON_LUCIDE_BOOK_HEART "\xee\x95\x88"  // U+E548
#define ICON_LUCIDE_BOOK_IMAGE "\xee\x95\x89"  // U+E549
#define ICON_LUCIDE_BOOK_KEY "\xee\x8f\xaf"  // U+E3EF
#define ICON_LUCIDE_BOOK_LOCK "\xee\x8f\xb0"  // U+E3F0
#define ICON_LUCIDE_BOOK_MARKED "\xee\x8f\xb1"  // U+E3F1
#define ICON_LUCIDE_BOOK_MINUS "\xee\x8f\xb2"  // U+E3F2
#define ICON_LUCIDE_BOOK_OPEN "\xee\x81\x9f"  // U+E05F
#define ICON_LUCIDE_BOOK_OPEN_CHECK "\xee\x8e\x81"  // U+E381
#define ICON_LUCIDE_BOOK_OPEN_TEXT "\xee\x95\x8a"  // U+E54A
#define ICON_LUCIDE_BOOK_PLUS "\xee\x8f\xb3"  // U+E3F3
#define ICON_LUCIDE_BOOK_SEARCH "\xee\x9a\xab"  // U+E6AB
#define ICON_LUCIDE_BOOK_TEXT "\xee\x95\x8b"  // U+E54B
#define ICON_LUCIDE_BOOK_TYPE "\xee\x95\x8c"  // U+E54C
#define ICON_LUCIDE_BOOK_UP "\xee\x8f\xb4"  // U+E3F4
#define ICON_LUCIDE_BOOK_UP_2 "\xee\x92\xa6"  // U+E4A6
#define ICON_LUCIDE_BOOK_USER "\xee\x95\x8d"  // U+E54D
#define ICON_LUCIDE_BOOK_X "\xee\x8f\xb5"  // U+E3F5
#define ICON_LUCIDE_BOOKMARK "\xee\x81\xa0"  // U+E060
#define ICON_LUCIDE_BOOKMARK_CHECK "\xee\x94\x9f"  // U+E51F
#define ICON_LUCIDE_BOOKMARK_MINUS "\xee\x88\xbc"  // U+E23C
#define ICON_LUCIDE_BOOKMARK_PLUS "\xee\x88\xbd"  // U+E23D
#define ICON_LUCIDE_BOOKMARK_X "\xee\x94\xa0"  // U+E520
#define ICON_LUCIDE_BOOM_BOX "\xee\x93\xae"  // U+E4EE
#define ICON_LUCIDE_BOT "\xee\x86\xbb"  // U+E1BB
#define ICON_LUCIDE_BOT_MESSAGE_SQUARE "\xee\x97\x8e"  // U+E5CE
#define ICON_LUCIDE_BOT_OFF "\xee\x97\xa0"  // U+E5E0
#define ICON_LUCIDE_BOTTLE_WINE "\xee\x99\xbb"  // U+E67B
#define ICON_LUCIDE_BOW_ARROW "\xee\x99\x9e"  // U+E65E
#define ICON_LUCIDE_BOX "\xee\x81\xa1"  // U+E061
#define ICON_LUCIDE_BOXES "\xee\x8b\x90"  // U+E2D0
#define ICON_LUCIDE_BRACES "\xee\x8d\xaa"  // U+E36A
#define ICON_LUCIDE_BRACKETS "\xee\x91\x83"  // U+E443
#define ICON_LUCIDE_BRAIN "\xee\x8f\x86"  // U+E3C6
#define ICON_LUCIDE_BRAIN_CIRCUIT "\xee\x8f\x87"  // U+E3C7
#define ICON_LUCIDE_BRAIN_COG "\xee\x8f\x88"  // U+E3C8
#define ICON_LUCIDE_BRICK_WALL "\xee\x96\x81"  // U+E581
#define ICON_LUCIDE_BRICK_WALL_FIRE "\xee\x99\x93"  // U+E653
#define ICON_LUCIDE_BRICK_WALL_SHIELD "\xee\x9a\x90"  // U+E690
#define ICON_LUCIDE_BRIEFCASE "\xee\x81\xa2"  // U+E062
#define ICON_LUCIDE_BRIEFCASE_BUSINESS "\xee\x97\x95"  // U+E5D5
#define ICON_LUCIDE_BRIEFCASE_CONVEYOR_BELT "\xee\x98\xab"  // U+E62B
#define ICON_LUCIDE_BRIEFCASE_MEDICAL "\xee\x97\x96"  // U+E5D6
#define ICON_LUCIDE_BRING_TO_FRONT "\xee\x93\xaf"  // U+E4EF
#define ICON_LUCIDE_BRUSH "\xee\x87\x93"  // U+E1D3
#define ICON_LUCIDE_BRUSH_CLEANING "\xee\x99\xa6"  // U+E666
#define ICON_LUCIDE_BUBBLES "\xee\x99\x94"  // U+E654
#define ICON_LUCIDE_BUG "\xee\x88\x8c"  // U+E20C
#define ICON_LUCIDE_BUG_OFF "\xee\x94\x8d"  // U+E50D
#define ICON_LUCIDE_BUG_PLAY "\xee\x94\x8e"  // U+E50E
#define ICON_LUCIDE_BUILDING "\xee\x87\x8c"  // U+E1CC
#define ICON_LUCIDE_BUILDING_2 "\xee\x8a\x90"  // U+E290
#define ICON_LUCIDE_BUS "\xee\x87\x94"  // U+E1D4
#define ICON_LUCIDE_BUS_FRONT "\xee\x93\xbb"  // U+E4FB
#define ICON_LUCIDE_CABLE "\xee\x93\xa3"  // U+E4E3
#define ICON_LUCIDE_CABLE_CAR "\xee\x93\xbc"  // U+E4FC
#define ICON_LUCIDE_CAKE "\xee\x8d\x84"  // U+E344
#define ICON_LUCIDE_CAKE_SLICE "\xee\x92\xb9"  // U+E4B9
#define ICON_LUCIDE_CALCULATOR "\xee\x86\xbc"  // U+E1BC
#define ICON_LUCIDE_CALENDAR "\xee\x81\xa3"  // U+E063
#define ICON_LUCIDE_CALENDAR_1 "\xee\x98\xb0"  // U+E630
#define ICON_LUCIDE_CALENDAR_ARROW_DOWN "\xee\x97\xbe"  // U+E5FE
#define ICON_LUCIDE_CALENDAR_ARROW_UP "\xee\x97\xbf"  // U+E5FF
#define ICON_LUCIDE_CALENDAR_CHECK "\xee\x8a\xb7"  // U+E2B7
#define ICON_LUCIDE_CALENDAR_CHECK_2 "\xee\x8a\xb8"  // U+E2B8
#define ICON_LUCIDE_CALENDAR_CLOCK "\xee\x8c\x84"  // U+E304
#define ICON_LUCIDE_CALENDAR_COG "\xee\x97\xad"  // U+E5ED
#define ICON_LUCIDE_CALENDAR_DAYS "\xee\x8a\xb9"  // U+E2B9
#define ICON_LUCIDE_CALENDAR_FOLD "\xee\x96\xb4"  // U+E5B4
#define ICON_LUCIDE_CALENDAR_HEART "\xee\x8c\x85"  // U+E305
#define ICON_LUCIDE_CALENDAR_MINUS "\xee\x8a\xba"  // U+E2BA
#define ICON_LUCIDE_CALENDAR_MINUS_2 "\xee\x96\xb5"  // U+E5B5
#define ICON_LUCIDE_CALENDAR_OFF "\xee\x8a\xbb"  // U+E2BB
#define ICON_LUCIDE_CALENDAR_PLUS "\xee\x8a\xbc"  // U+E2BC
#define ICON_LUCIDE_CALENDAR_PLUS_2 "\xee\x96\xb6"  // U+E5B6
#define ICON_LUCIDE_CALENDAR_RANGE "\xee\x8a\xbd"  // U+E2BD
#define ICON_LUCIDE_CALENDAR_SEARCH "\xee\x8c\x86"  // U+E306
#define ICON_LUCIDE_CALENDAR_SYNC "\xee\x98\xb6"  // U+E636
#define ICON_LUCIDE_CALENDAR_X "\xee\x8a\xbe"  // U+E2BE
#define ICON_LUCIDE_CALENDAR_X_2 "\xee\x8a\xbf"  // U+E2BF
#define ICON_LUCIDE_CALENDARS "\xee\x9a\xa7"  // U+E6A7
#define ICON_LUCIDE_CAMERA "\xee\x81\xa4"  // U+E064
#define ICON_LUCIDE_CAMERA_OFF "\xee\x81\xa5"  // U+E065
#define ICON_LUCIDE_CANDY "\xee\x8e\x91"  // U+E391
#define ICON_LUCIDE_CANDY_CANE "\xee\x92\xba"  // U+E4BA
#define ICON_LUCIDE_CANDY_OFF "\xee\x8e\x92"  // U+E392
#define ICON_LUCIDE_CANNABIS "\xee\x97\x94"  // U+E5D4
#define ICON_LUCIDE_CANNABIS_OFF "\xee\x9a\xb7"  // U+E6B7
#define ICON_LUCIDE_CAPTIONS "\xee\x8e\xa4"  // U+E3A4
#define ICON_LUCIDE_CAPTIONS_OFF "\xee\x97\x81"  // U+E5C1
#define ICON_LUCIDE_CAR "\xee\x87\x95"  // U+E1D5
#define ICON_LUCIDE_CAR_FRONT "\xee\x93\xbd"  // U+E4FD
#define ICON_LUCIDE_CAR_TAXI_FRONT "\xee\x93\xbe"  // U+E4FE
#define ICON_LUCIDE_CARAVAN "\xee\x94\xb9"  // U+E539
#define ICON_LUCIDE_CARD_SIM "\xee\x99\xb1"  // U+E671
#define ICON_LUCIDE_CARROT "\xee\x89\x9a"  // U+E25A
#define ICON_LUCIDE_CASE_LOWER "\xee\x8f\x98"  // U+E3D8
#define ICON_LUCIDE_CASE_SENSITIVE "\xee\x8f\x99"  // U+E3D9
#define ICON_LUCIDE_CASE_UPPER "\xee\x8f\x9a"  // U+E3DA
#define ICON_LUCIDE_CASSETTE_TAPE "\xee\x93\x8a"  // U+E4CA
#define ICON_LUCIDE_CAST "\xee\x81\xa6"  // U+E066
#define ICON_LUCIDE_CASTLE "\xee\x8f\xa0"  // U+E3E0
#define ICON_LUCIDE_CAT "\xee\x8e\x8c"  // U+E38C
#define ICON_LUCIDE_CCTV "\xee\x95\xbd"  // U+E57D
#define ICON_LUCIDE_CHART_AREA "\xee\x93\x93"  // U+E4D3
#define ICON_LUCIDE_CHART_BAR "\xee\x8a\xa2"  // U+E2A2
#define ICON_LUCIDE_CHART_BAR_BIG "\xee\x92\xa7"  // U+E4A7
#define ICON_LUCIDE_CHART_BAR_DECREASING "\xee\x98\x87"  // U+E607
#define ICON_LUCIDE_CHART_BAR_INCREASING "\xee\x98\x88"  // U+E608
#define ICON_LUCIDE_CHART_BAR_STACKED "\xee\x98\x89"  // U+E609
#define ICON_LUCIDE_CHART_CANDLESTICK "\xee\x92\xa8"  // U+E4A8
#define ICON_LUCIDE_CHART_COLUMN "\xee\x8a\xa3"  // U+E2A3
#define ICON_LUCIDE_CHART_COLUMN_BIG "\xee\x92\xa9"  // U+E4A9
#define ICON_LUCIDE_CHART_COLUMN_DECREASING "\xee\x81\xa7"  // U+E067
#define ICON_LUCIDE_CHART_COLUMN_INCREASING "\xee\x8a\xa4"  // U+E2A4
#define ICON_LUCIDE_CHART_COLUMN_STACKED "\xee\x98\x8a"  // U+E60A
#define ICON_LUCIDE_CHART_GANTT "\xee\x98\xa4"  // U+E624
#define ICON_LUCIDE_CHART_LINE "\xee\x8a\xa5"  // U+E2A5
#define ICON_LUCIDE_CHART_NETWORK "\xee\x98\x8b"  // U+E60B
#define ICON_LUCIDE_CHART_NO_AXES_COLUMN "\xee\x81\xa8"  // U+E068
#define ICON_LUCIDE_CHART_NO_AXES_COLUMN_DECREASING "\xee\x81\xa9"  // U+E069
#define ICON_LUCIDE_CHART_NO_AXES_COLUMN_INCREASING "\xee\x81\xaa"  // U+E06A
#define ICON_LUCIDE_CHART_NO_AXES_COMBINED "\xee\x98\x8c"  // U+E60C
#define ICON_LUCIDE_CHART_NO_AXES_GANTT "\xee\x93\x84"  // U+E4C4
#define ICON_LUCIDE_CHART_PIE "\xee\x81\xab"  // U+E06B
#define ICON_LUCIDE_CHART_SCATTER "\xee\x92\x8a"  // U+E48A
#define ICON_LUCIDE_CHART_SPLINE "\xee\x98\x8d"  // U+E60D
#define ICON_LUCIDE_CHECK "\xee\x81\xac"  // U+E06C
#define ICON_LUCIDE_CHECK_CHECK "\xee\x8e\x8e"  // U+E38E
#define ICON_LUCIDE_CHECK_LINE "\xee\x99\xab"  // U+E66B
#define ICON_LUCIDE_CHEF_HAT "\xee\x8a\xac"  // U+E2AC
#define ICON_LUCIDE_CHERRY "\xee\x8d\x90"  // U+E350
#define ICON_LUCIDE_CHESS_BISHOP "\xee\x9a\xa0"  // U+E6A0
#define ICON_LUCIDE_CHESS_KING "\xee\x9a\xa1"  // U+E6A1
#define ICON_LUCIDE_CHESS_KNIGHT "\xee\x9a\xa2"  // U+E6A2
#define ICON_LUCIDE_CHESS_PAWN "\xee\x9a\xa3"  // U+E6A3
#define ICON_LUCIDE_CHESS_QUEEN "\xee\x9a\xa4"  // U+E6A4
#define ICON_LUCIDE_CHESS_ROOK "\xee\x9a\xa5"  // U+E6A5
#define ICON_LUCIDE_CHEVRON_DOWN "\xee\x81\xad"  // U+E06D
#define ICON_LUCIDE_CHEVRON_FIRST "\xee\x89\x83"  // U+E243
#define ICON_LUCIDE_CHEVRON_LAST "\xee\x89\x84"  // U+E244
#define ICON_LUCIDE_CHEVRON_LEFT "\xee\x81\xae"  // U+E06E
#define ICON_LUCIDE_CHEVRON_RIGHT "\xee\x81\xaf"  // U+E06F
#define ICON_LUCIDE_CHEVRON_UP "\xee\x81\xb0"  // U+E070
#define ICON_LUCIDE_CHEVRONS_DOWN "\xee\x81\xb1"  // U+E071
#define ICON_LUCIDE_CHEVRONS_DOWN_UP "\xee\x88\xa8"  // U+E228
#define ICON_LUCIDE_CHEVRONS_LEFT "\xee\x81\xb2"  // U+E072
#define ICON_LUCIDE_CHEVRONS_LEFT_RIGHT "\xee\x8a\x93"  // U+E293
#define ICON_LUCIDE_CHEVRONS_LEFT_RIGHT_ELLIPSIS "\xee\x98\x9f"  // U+E61F
#define ICON_LUCIDE_CHEVRONS_RIGHT "\xee\x81\xb3"  // U+E073
#define ICON_LUCIDE_CHEVRONS_RIGHT_LEFT "\xee\x8a\x94"  // U+E294
#define ICON_LUCIDE_CHEVRONS_UP "\xee\x81\xb4"  // U+E074
#define ICON_LUCIDE_CHEVRONS_UP_DOWN "\xee\x88\x91"  // U+E211
#define ICON_LUCIDE_CHROMIUM "\xee\x81\xb5"  // U+E075
#define ICON_LUCIDE_CHURCH "\xee\x8f\xa1"  // U+E3E1
#define ICON_LUCIDE_CIGARETTE "\xee\x8b\x86"  // U+E2C6
#define ICON_LUCIDE_CIGARETTE_OFF "\xee\x8b\x87"  // U+E2C7
#define ICON_LUCIDE_CIRCLE "\xee\x81\xb6"  // U+E076
#define ICON_LUCIDE_CIRCLE_ALERT "\xee\x81\xb7"  // U+E077
#define ICON_LUCIDE_CIRCLE_ARROW_DOWN "\xee\x81\xb8"  // U+E078
#define ICON_LUCIDE_CIRCLE_ARROW_LEFT "\xee\x81\xb9"  // U+E079
#define ICON_LUCIDE_CIRCLE_ARROW_OUT_DOWN_LEFT "\xee\x8f\xb7"  // U+E3F7
#define ICON_LUCIDE_CIRCLE_ARROW_OUT_DOWN_RIGHT "\xee\x8f\xb8"  // U+E3F8
#define ICON_LUCIDE_CIRCLE_ARROW_OUT_UP_LEFT "\xee\x8f\xb9"  // U+E3F9
#define ICON_LUCIDE_CIRCLE_ARROW_OUT_UP_RIGHT "\xee\x8f\xba"  // U+E3FA
#define ICON_LUCIDE_CIRCLE_ARROW_RIGHT "\xee\x81\xba"  // U+E07A
#define ICON_LUCIDE_CIRCLE_ARROW_UP "\xee\x81\xbb"  // U+E07B
#define ICON_LUCIDE_CIRCLE_CHECK "\xee\x88\xa6"  // U+E226
#define ICON_LUCIDE_CIRCLE_CHECK_BIG "\xee\x81\xbc"  // U+E07C
#define ICON_LUCIDE_CIRCLE_CHEVRON_DOWN "\xee\x93\x9d"  // U+E4DD
#define ICON_LUCIDE_CIRCLE_CHEVRON_LEFT "\xee\x93\x9e"  // U+E4DE
#define ICON_LUCIDE_CIRCLE_CHEVRON_RIGHT "\xee\x93\x9f"  // U+E4DF
#define ICON_LUCIDE_CIRCLE_CHEVRON_UP "\xee\x93\xa0"  // U+E4E0
#define ICON_LUCIDE_CIRCLE_DASHED "\xee\x92\xb0"  // U+E4B0
#define ICON_LUCIDE_CIRCLE_DIVIDE "\xee\x81\xbd"  // U+E07D
#define ICON_LUCIDE_CIRCLE_DOLLAR_SIGN "\xee\x91\xbd"  // U+E47D
#define ICON_LUCIDE_CIRCLE_DOT "\xee\x8d\x85"  // U+E345
#define ICON_LUCIDE_CIRCLE_DOT_DASHED "\xee\x92\xb1"  // U+E4B1
#define ICON_LUCIDE_CIRCLE_ELLIPSIS "\xee\x8d\x86"  // U+E346
#define ICON_LUCIDE_CIRCLE_EQUAL "\xee\x90\x80"  // U+E400
#define ICON_LUCIDE_CIRCLE_FADING_ARROW_UP "\xee\x98\x98"  // U+E618
#define ICON_LUCIDE_CIRCLE_FADING_PLUS "\xee\x96\xbc"  // U+E5BC
#define ICON_LUCIDE_CIRCLE_GAUGE "\xee\x93\xa1"  // U+E4E1
#define ICON_LUCIDE_CIRCLE_MINUS "\xee\x81\xbe"  // U+E07E
#define ICON_LUCIDE_CIRCLE_OFF "\xee\x90\x81"  // U+E401
#define ICON_LUCIDE_CIRCLE_PARKING "\xee\x8f\x89"  // U+E3C9
#define ICON_LUCIDE_CIRCLE_PARKING_OFF "\xee\x8f\x8a"  // U+E3CA
#define ICON_LUCIDE_CIRCLE_PAUSE "\xee\x81\xbf"  // U+E07F
#define ICON_LUCIDE_CIRCLE_PERCENT "\xee\x94\x9a"  // U+E51A
#define ICON_LUCIDE_CIRCLE_PILE "\xee\x9a\xb0"  // U+E6B0
#define ICON_LUCIDE_CIRCLE_PLAY "\xee\x82\x80"  // U+E080
#define ICON_LUCIDE_CIRCLE_PLUS "\xee\x82\x81"  // U+E081
#define ICON_LUCIDE_CIRCLE_POUND_STERLING "\xee\x99\xad"  // U+E66D
#define ICON_LUCIDE_CIRCLE_POWER "\xee\x95\x90"  // U+E550
#define ICON_LUCIDE_CIRCLE_QUESTION_MARK "\xee\x82\x82"  // U+E082
#define ICON_LUCIDE_CIRCLE_SLASH "\xee\x90\x82"  // U+E402
#define ICON_LUCIDE_CIRCLE_SLASH_2 "\xee\x88\x93"  // U+E213
#define ICON_LUCIDE_CIRCLE_SMALL "\xee\x99\x80"  // U+E640
#define ICON_LUCIDE_CIRCLE_STAR "\xee\x9a\x8d"  // U+E68D
#define ICON_LUCIDE_CIRCLE_STOP "\xee\x82\x83"  // U+E083
#define ICON_LUCIDE_CIRCLE_USER "\xee\x91\xa1"  // U+E461
#define ICON_LUCIDE_CIRCLE_USER_ROUND "\xee\x91\xa2"  // U+E462
#define ICON_LUCIDE_CIRCLE_X "\xee\x82\x84"  // U+E084
#define ICON_LUCIDE_CIRCUIT_BOARD "\xee\x90\x83"  // U+E403
#define ICON_LUCIDE_CITRUS "\xee\x8d\xb5"  // U+E375
#define ICON_LUCIDE_CLAPPERBOARD "\xee\x8a\x9b"  // U+E29B
#define ICON_LUCIDE_CLIPBOARD "\xee\x82\x85"  // U+E085
#define ICON_LUCIDE_CLIPBOARD_CHECK "\xee\x88\x99"  // U+E219
#define ICON_LUCIDE_CLIPBOARD_CLOCK "\xee\x9a\x88"  // U+E688
#define ICON_LUCIDE_CLIPBOARD_COPY "\xee\x88\xa5"  // U+E225
#define ICON_LUCIDE_CLIPBOARD_LIST "\xee\x82\x86"  // U+E086
#define ICON_LUCIDE_CLIPBOARD_MINUS "\xee\x96\xbe"  // U+E5BE
#define ICON_LUCIDE_CLIPBOARD_PASTE "\xee\x8f\xa8"  // U+E3E8
#define ICON_LUCIDE_CLIPBOARD_PEN "\xee\x8c\x87"  // U+E307
#define ICON_LUCIDE_CLIPBOARD_PEN_LINE "\xee\x8c\x88"  // U+E308
#define ICON_LUCIDE_CLIPBOARD_PLUS "\xee\x96\xbf"  // U+E5BF
#define ICON_LUCIDE_CLIPBOARD_TYPE "\xee\x8c\x89"  // U+E309
#define ICON_LUCIDE_CLIPBOARD_X "\xee\x88\xa2"  // U+E222
#define ICON_LUCIDE_CLOCK "\xee\x82\x87"  // U+E087
#define ICON_LUCIDE_CLOCK_1 "\xee\x89\x8b"  // U+E24B
#define ICON_LUCIDE_CLOCK_10 "\xee\x89\x8c"  // U+E24C
#define ICON_LUCIDE_CLOCK_11 "\xee\x89\x8d"  // U+E24D
#define ICON_LUCIDE_CLOCK_12 "\xee\x89\x8e"  // U+E24E
#define ICON_LUCIDE_CLOCK_2 "\xee\x89\x8f"  // U+E24F
#define ICON_LUCIDE_CLOCK_3 "\xee\x89\x90"  // U+E250
#define ICON_LUCIDE_CLOCK_4 "\xee\x89\x91"  // U+E251
#define ICON_LUCIDE_CLOCK_5 "\xee\x89\x92"  // U+E252
#define ICON_LUCIDE_CLOCK_6 "\xee\x89\x93"  // U+E253
#define ICON_LUCIDE_CLOCK_7 "\xee\x89\x94"  // U+E254
#define ICON_LUCIDE_CLOCK_8 "\xee\x89\x95"  // U+E255
#define ICON_LUCIDE_CLOCK_9 "\xee\x89\x96"  // U+E256
#define ICON_LUCIDE_CLOCK_ALERT "\xee\x98\xaa"  // U+E62A
#define ICON_LUCIDE_CLOCK_ARROW_DOWN "\xee\x98\x80"  // U+E600
#define ICON_LUCIDE_CLOCK_ARROW_UP "\xee\x98\x81"  // U+E601
#define ICON_LUCIDE_CLOCK_CHECK "\xee\x9a\x9e"  // U+E69E
#define ICON_LUCIDE_CLOCK_FADING "\xee\x99\x8a"  // U+E64A
#define ICON_LUCIDE_CLOCK_PLUS "\xee\x99\xa7"  // U+E667
#define ICON_LUCIDE_CLOSED_CAPTION "\xee\x9a\x8a"  // U+E68A
#define ICON_LUCIDE_CLOUD "\xee\x82\x88"  // U+E088
#define ICON_LUCIDE_CLOUD_ALERT "\xee\x98\xb3"  // U+E633
#define ICON_LUCIDE_CLOUD_BACKUP "\xee\x9a\xb1"  // U+E6B1
#define ICON_LUCIDE_CLOUD_CHECK "\xee\x99\xae"  // U+E66E
#define ICON_LUCIDE_CLOUD_COG "\xee\x8c\x8a"  // U+E30A
#define ICON_LUCIDE_CLOUD_DOWNLOAD "\xee\x82\x89"  // U+E089
#define ICON_LUCIDE_CLOUD_DRIZZLE "\xee\x82\x8a"  // U+E08A
#define ICON_LUCIDE_CLOUD_FOG "\xee\x88\x94"  // U+E214
#define ICON_LUCIDE_CLOUD_HAIL "\xee\x82\x8b"  // U+E08B
#define ICON_LUCIDE_CLOUD_LIGHTNING "\xee\x82\x8c"  // U+E08C
#define ICON_LUCIDE_CLOUD_MOON "\xee\x88\x95"  // U+E215
#define ICON_LUCIDE_CLOUD_MOON_RAIN "\xee\x8b\xba"  // U+E2FA
#define ICON_LUCIDE_CLOUD_OFF "\xee\x82\x8d"  // U+E08D
#define ICON_LUCIDE_CLOUD_RAIN "\xee\x82\x8e"  // U+E08E
#define ICON_LUCIDE_CLOUD_RAIN_WIND "\xee\x82\x8f"  // U+E08F
#define ICON_LUCIDE_CLOUD_SNOW "\xee\x82\x90"  // U+E090
#define ICON_LUCIDE_CLOUD_SUN "\xee\x88\x96"  // U+E216
#define ICON_LUCIDE_CLOUD_SUN_RAIN "\xee\x8b\xbb"  // U+E2FB
#define ICON_LUCIDE_CLOUD_SYNC "\xee\x9a\xb2"  // U+E6B2
#define ICON_LUCIDE_CLOUD_UPLOAD "\xee\x82\x91"  // U+E091
#define ICON_LUCIDE_CLOUDY "\xee\x88\x97"  // U+E217
#define ICON_LUCIDE_CLOVER "\xee\x82\x92"  // U+E092
#define ICON_LUCIDE_CLUB "\xee\x92\x96"  // U+E496
#define ICON_LUCIDE_CODE "\xee\x82\x93"  // U+E093
#define ICON_LUCIDE_CODE_XML "\xee\x88\x86"  // U+E206
#define ICON_LUCIDE_CODEPEN "\xee\x82\x94"  // U+E094
#define ICON_LUCIDE_CODESANDBOX "\xee\x82\x95"  // U+E095
#define ICON_LUCIDE_COFFEE "\xee\x82\x96"  // U+E096
#define ICON_LUCIDE_COG "\xee\x8c\x8b"  // U+E30B
#define ICON_LUCIDE_COINS "\xee\x82\x97"  // U+E097
#define ICON_LUCIDE_COLUMNS_2 "\xee\x82\x98"  // U+E098
#define ICON_LUCIDE_COLUMNS_3 "\xee\x82\x99"  // U+E099
#define ICON_LUCIDE_COLUMNS_3_COG "\xee\x99\xa1"  // U+E661
#define ICON_LUCIDE_COLUMNS_4 "\xee\x96\x89"  // U+E589
#define ICON_LUCIDE_COMBINE "\xee\x91\x8c"  // U+E44C
#define ICON_LUCIDE_COMMAND "\xee\x82\x9a"  // U+E09A
#define ICON_LUCIDE_COMPASS "\xee\x82\x9b"  // U+E09B
#define ICON_LUCIDE_COMPONENT "\xee\x8a\xad"  // U+E2AD
#define ICON_LUCIDE_COMPUTER "\xee\x93\xa4"  // U+E4E4
#define ICON_LUCIDE_CONCIERGE_BELL "\xee\x8d\xb8"  // U+E378
#define ICON_LUCIDE_CONE "\xee\x94\xa3"  // U+E523
#define ICON_LUCIDE_CONSTRUCTION "\xee\x8e\xb4"  // U+E3B4
#define ICON_LUCIDE_CONTACT "\xee\x82\x9c"  // U+E09C
#define ICON_LUCIDE_CONTACT_ROUND "\xee\x91\xa3"  // U+E463
#define ICON_LUCIDE_CONTAINER "\xee\x93\x95"  // U+E4D5
#define ICON_LUCIDE_CONTRAST "\xee\x82\x9d"  // U+E09D
#define ICON_LUCIDE_COOKIE "\xee\x89\xab"  // U+E26B
#define ICON_LUCIDE_COOKING_POT "\xee\x96\x84"  // U+E584
#define ICON_LUCIDE_COPY "\xee\x82\x9e"  // U+E09E
#define ICON_LUCIDE_COPY_CHECK "\xee\x8f\xbb"  // U+E3FB
#define ICON_LUCIDE_COPY_MINUS "\xee\x8f\xbc"  // U+E3FC
#define ICON_LUCIDE_COPY_PLUS "\xee\x8f\xbd"  // U+E3FD
#define ICON_LUCIDE_COPY_SLASH "\xee\x8f\xbe"  // U+E3FE
#define ICON_LUCIDE_COPY_X "\xee\x8f\xbf"  // U+E3FF
#define ICON_LUCIDE_COPYLEFT "\xee\x82\x9f"  // U+E09F
#define ICON_LUCIDE_COPYRIGHT "\xee\x82\xa0"  // U+E0A0
#define ICON_LUCIDE_CORNER_DOWN_LEFT "\xee\x82\xa1"  // U+E0A1
#define ICON_LUCIDE_CORNER_DOWN_RIGHT "\xee\x82\xa2"  // U+E0A2
#define ICON_LUCIDE_CORNER_LEFT_DOWN "\xee\x82\xa3"  // U+E0A3
#define ICON_LUCIDE_CORNER_LEFT_UP "\xee\x82\xa4"  // U+E0A4
#define ICON_LUCIDE_CORNER_RIGHT_DOWN "\xee\x82\xa5"  // U+E0A5
#define ICON_LUCIDE_CORNER_RIGHT_UP "\xee\x82\xa6"  // U+E0A6
#define ICON_LUCIDE_CORNER_UP_LEFT "\xee\x82\xa7"  // U+E0A7
#define ICON_LUCIDE_CORNER_UP_RIGHT "\xee\x82\xa8"  // U+E0A8
#define ICON_LUCIDE_CPU "\xee\x82\xa9"  // U+E0A9
#define ICON_LUCIDE_CREATIVE_COMMONS "\xee\x8e\xb2"  // U+E3B2
#define ICON_LUCIDE_CREDIT_CARD "\xee\x82\xaa"  // U+E0AA
#define ICON_LUCIDE_CROISSANT "\xee\x8a\xae"  // U+E2AE
#define ICON_LUCIDE_CROP "\xee\x82\xab"  // U+E0AB
#define ICON_LUCIDE_CROSS "\xee\x87\xa5"  // U+E1E5
#define ICON_LUCIDE_CROSSHAIR "\xee\x82\xac"  // U+E0AC
#define ICON_LUCIDE_CROWN "\xee\x87\x96"  // U+E1D6
#define ICON_LUCIDE_CUBOID "\xee\x94\xa4"  // U+E524
#define ICON_LUCIDE_CUP_SODA "\xee\x8b\x91"  // U+E2D1
#define ICON_LUCIDE_CURRENCY "\xee\x88\xb0"  // U+E230
#define ICON_LUCIDE_CYLINDER "\xee\x94\xa5"  // U+E525
#define ICON_LUCIDE_DAM "\xee\x98\x86"  // U+E606
#define ICON_LUCIDE_DATABASE "\xee\x82\xad"  // U+E0AD
#define ICON_LUCIDE_DATABASE_BACKUP "\xee\x8e\xab"  // U+E3AB
#define ICON_LUCIDE_DATABASE_SEARCH "\xee\x9a\xbc"  // U+E6BC
#define ICON_LUCIDE_DATABASE_ZAP "\xee\x94\x8b"  // U+E50B
#define ICON_LUCIDE_DECIMALS_ARROW_LEFT "\xee\x99\x9c"  // U+E65C
#define ICON_LUCIDE_DECIMALS_ARROW_RIGHT "\xee\x99\x9d"  // U+E65D
#define ICON_LUCIDE_DELETE "\xee\x82\xae"  // U+E0AE
#define ICON_LUCIDE_DESSERT "\xee\x92\xbb"  // U+E4BB
#define ICON_LUCIDE_DIAMETER "\xee\x94\xa6"  // U+E526
#define ICON_LUCIDE_DIAMOND "\xee\x8b\x92"  // U+E2D2
#define ICON_LUCIDE_DIAMOND_MINUS "\xee\x97\xa1"  // U+E5E1
#define ICON_LUCIDE_DIAMOND_PERCENT "\xee\x94\x9b"  // U+E51B
#define ICON_LUCIDE_DIAMOND_PLUS "\xee\x97\xa2"  // U+E5E2
#define ICON_LUCIDE_DICE_1 "\xee\x8a\x87"  // U+E287
#define ICON_LUCIDE_DICE_2 "\xee\x8a\x88"  // U+E288
#define ICON_LUCIDE_DICE_3 "\xee\x8a\x89"  // U+E289
#define ICON_LUCIDE_DICE_4 "\xee\x8a\x8a"  // U+E28A
#define ICON_LUCIDE_DICE_5 "\xee\x8a\x8b"  // U+E28B
#define ICON_LUCIDE_DICE_6 "\xee\x8a\x8c"  // U+E28C
#define ICON_LUCIDE_DICES "\xee\x8b\x85"  // U+E2C5
#define ICON_LUCIDE_DIFF "\xee\x8c\x8c"  // U+E30C
#define ICON_LUCIDE_DISC "\xee\x82\xaf"  // U+E0AF
#define ICON_LUCIDE_DISC_2 "\xee\x8f\xb6"  // U+E3F6
#define ICON_LUCIDE_DISC_3 "\xee\x92\x94"  // U+E494
#define ICON_LUCIDE_DISC_ALBUM "\xee\x95\x9c"  // U+E55C
#define ICON_LUCIDE_DIVIDE "\xee\x82\xb0"  // U+E0B0
#define ICON_LUCIDE_DNA "\xee\x8e\x93"  // U+E393
#define ICON_LUCIDE_DNA_OFF "\xee\x8e\x94"  // U+E394
#define ICON_LUCIDE_DOCK "\xee\x97\x93"  // U+E5D3
#define ICON_LUCIDE_DOG "\xee\x8e\x8d"  // U+E38D
#define ICON_LUCIDE_DOLLAR_SIGN "\xee\x82\xb1"  // U+E0B1
#define ICON_LUCIDE_DONUT "\xee\x92\xbc"  // U+E4BC
#define ICON_LUCIDE_DOOR_CLOSED "\xee\x8f\x95"  // U+E3D5
#define ICON_LUCIDE_DOOR_CLOSED_LOCKED "\xee\x99\xa4"  // U+E664
#define ICON_LUCIDE_DOOR_OPEN "\xee\x8f\x96"  // U+E3D6
#define ICON_LUCIDE_DOT "\xee\x91\x8f"  // U+E44F
#define ICON_LUCIDE_DOWNLOAD "\xee\x82\xb2"  // U+E0B2
#define ICON_LUCIDE_DRAFTING_COMPASS "\xee\x94\xa7"  // U+E527
#define ICON_LUCIDE_DRAMA "\xee\x94\xa1"  // U+E521
#define ICON_LUCIDE_DRIBBBLE "\xee\x82\xb3"  // U+E0B3
#define ICON_LUCIDE_DRILL "\xee\x96\x8d"  // U+E58D
#define ICON_LUCIDE_DRONE "\xee\x99\xb6"  // U+E676
#define ICON_LUCIDE_DROPLET "\xee\x82\xb4"  // U+E0B4
#define ICON_LUCIDE_DROPLET_OFF "\xee\x98\xb8"  // U+E638
#define ICON_LUCIDE_DROPLETS "\xee\x82\xb5"  // U+E0B5
#define ICON_LUCIDE_DRUM "\xee\x95\x9d"  // U+E55D
#define ICON_LUCIDE_DRUMSTICK "\xee\x89\x9b"  // U+E25B
#define ICON_LUCIDE_DUMBBELL "\xee\x8e\xa1"  // U+E3A1
#define ICON_LUCIDE_EAR "\xee\x8e\x82"  // U+E382
#define ICON_LUCIDE_EAR_OFF "\xee\x8e\x83"  // U+E383
#define ICON_LUCIDE_EARTH "\xee\x87\xb3"  // U+E1F3
#define ICON_LUCIDE_EARTH_LOCK "\xee\x97\x8c"  // U+E5CC
#define ICON_LUCIDE_ECLIPSE "\xee\x96\x9d"  // U+E59D
#define ICON_LUCIDE_EGG "\xee\x89\x9d"  // U+E25D
#define ICON_LUCIDE_EGG_FRIED "\xee\x8d\x91"  // U+E351
#define ICON_LUCIDE_EGG_OFF "\xee\x8e\x95"  // U+E395
#define ICON_LUCIDE_ELLIPSIS "\xee\x82\xb6"  // U+E0B6
#define ICON_LUCIDE_ELLIPSIS_VERTICAL "\xee\x82\xb7"  // U+E0B7
#define ICON_LUCIDE_EQUAL "\xee\x86\xbd"  // U+E1BD
#define ICON_LUCIDE_EQUAL_APPROXIMATELY "\xee\x98\xb4"  // U+E634
#define ICON_LUCIDE_EQUAL_NOT "\xee\x86\xbe"  // U+E1BE
#define ICON_LUCIDE_ERASER "\xee\x8a\x8f"  // U+E28F
#define ICON_LUCIDE_ETHERNET_PORT "\xee\x98\xa0"  // U+E620
#define ICON_LUCIDE_EURO "\xee\x82\xb8"  // U+E0B8
#define ICON_LUCIDE_EV_CHARGER "\xee\x9a\x97"  // U+E697
#define ICON_LUCIDE_EXPAND "\xee\x88\x9a"  // U+E21A
#define ICON_LUCIDE_EXTERNAL_LINK "\xee\x82\xb9"  // U+E0B9
#define ICON_LUCIDE_EYE "\xee\x82\xba"  // U+E0BA
#define ICON_LUCIDE_EYE_CLOSED "\xee\x98\xae"  // U+E62E
#define ICON_LUCIDE_EYE_OFF "\xee\x82\xbb"  // U+E0BB
#define ICON_LUCIDE_FACEBOOK "\xee\x82\xbc"  // U+E0BC
#define ICON_LUCIDE_FACTORY "\xee\x8a\x9f"  // U+E29F
#define ICON_LUCIDE_FAN "\xee\x8d\xb9"  // U+E379
#define ICON_LUCIDE_FAST_FORWARD "\xee\x82\xbd"  // U+E0BD
#define ICON_LUCIDE_FEATHER "\xee\x82\xbe"  // U+E0BE
#define ICON_LUCIDE_FENCE "\xee\x96\x82"  // U+E582
#define ICON_LUCIDE_FERRIS_WHEEL "\xee\x91\xbf"  // U+E47F
#define ICON_LUCIDE_FIGMA "\xee\x82\xbf"  // U+E0BF
#define ICON_LUCIDE_FILE "\xee\x83\x80"  // U+E0C0
#define ICON_LUCIDE_FILE_ARCHIVE "\xee\x8c\x8d"  // U+E30D
#define ICON_LUCIDE_FILE_AXIS_3D "\xee\x8c\x8e"  // U+E30E
#define ICON_LUCIDE_FILE_BADGE "\xee\x8c\x8f"  // U+E30F
#define ICON_LUCIDE_FILE_BOX "\xee\x8c\x90"  // U+E310
#define ICON_LUCIDE_FILE_BRACES "\xee\x8d\xab"  // U+E36B
#define ICON_LUCIDE_FILE_BRACES_CORNER "\xee\x8d\xac"  // U+E36C
#define ICON_LUCIDE_FILE_CHART_COLUMN "\xee\x8c\x91"  // U+E311
#define ICON_LUCIDE_FILE_CHART_COLUMN_INCREASING "\xee\x8c\x92"  // U+E312
#define ICON_LUCIDE_FILE_CHART_LINE "\xee\x8c\x93"  // U+E313
#define ICON_LUCIDE_FILE_CHART_PIE "\xee\x8c\x94"  // U+E314
#define ICON_LUCIDE_FILE_CHECK "\xee\x83\x81"  // U+E0C1
#define ICON_LUCIDE_FILE_CHECK_CORNER "\xee\x83\x82"  // U+E0C2
#define ICON_LUCIDE_FILE_CLOCK "\xee\x8c\x95"  // U+E315
#define ICON_LUCIDE_FILE_CODE "\xee\x83\x83"  // U+E0C3
#define ICON_LUCIDE_FILE_CODE_CORNER "\xee\x91\x9e"  // U+E45E
#define ICON_LUCIDE_FILE_COG "\xee\x8c\x96"  // U+E316
#define ICON_LUCIDE_FILE_DIFF "\xee\x8c\x97"  // U+E317
#define ICON_LUCIDE_FILE_DIGIT "\xee\x83\x84"  // U+E0C4
#define ICON_LUCIDE_FILE_DOWN "\xee\x8c\x98"  // U+E318
#define ICON_LUCIDE_FILE_EXCLAMATION_POINT "\xee\x8c\x99"  // U+E319
#define ICON_LUCIDE_FILE_HEADPHONE "\xee\x8c\x9a"  // U+E31A
#define ICON_LUCIDE_FILE_HEART "\xee\x8c\x9b"  // U+E31B
#define ICON_LUCIDE_FILE_IMAGE "\xee\x8c\x9c"  // U+E31C
#define ICON_LUCIDE_FILE_INPUT "\xee\x83\x85"  // U+E0C5
#define ICON_LUCIDE_FILE_KEY "\xee\x8c\x9d"  // U+E31D
#define ICON_LUCIDE_FILE_LOCK "\xee\x8c\x9e"  // U+E31E
#define ICON_LUCIDE_FILE_MINUS "\xee\x83\x86"  // U+E0C6
#define ICON_LUCIDE_FILE_MINUS_CORNER "\xee\x83\x87"  // U+E0C7
#define ICON_LUCIDE_FILE_MUSIC "\xee\x95\x9e"  // U+E55E
#define ICON_LUCIDE_FILE_OUTPUT "\xee\x83\x88"  // U+E0C8
#define ICON_LUCIDE_FILE_PEN "\xee\x8c\x9f"  // U+E31F
#define ICON_LUCIDE_FILE_PEN_LINE "\xee\x8c\xa0"  // U+E320
#define ICON_LUCIDE_FILE_PLAY "\xee\x8c\xa1"  // U+E321
#define ICON_LUCIDE_FILE_PLUS "\xee\x83\x89"  // U+E0C9
#define ICON_LUCIDE_FILE_PLUS_CORNER "\xee\x83\x8a"  // U+E0CA
#define ICON_LUCIDE_FILE_QUESTION_MARK "\xee\x8c\xa2"  // U+E322
#define ICON_LUCIDE_FILE_SCAN "\xee\x8c\xa3"  // U+E323
#define ICON_LUCIDE_FILE_SEARCH "\xee\x83\x8b"  // U+E0CB
#define ICON_LUCIDE_FILE_SEARCH_CORNER "\xee\x8c\xa4"  // U+E324
#define ICON_LUCIDE_FILE_SIGNAL "\xee\x8c\xa5"  // U+E325
#define ICON_LUCIDE_FILE_SLIDERS "\xee\x96\xa0"  // U+E5A0
#define ICON_LUCIDE_FILE_SPREADSHEET "\xee\x8c\xa6"  // U+E326
#define ICON_LUCIDE_FILE_STACK "\xee\x92\xa1"  // U+E4A1
#define ICON_LUCIDE_FILE_SYMLINK "\xee\x8c\xa7"  // U+E327
#define ICON_LUCIDE_FILE_TERMINAL "\xee\x8c\xa8"  // U+E328
#define ICON_LUCIDE_FILE_TEXT "\xee\x83\x8c"  // U+E0CC
#define ICON_LUCIDE_FILE_TYPE "\xee\x8c\xa9"  // U+E329
#define ICON_LUCIDE_FILE_TYPE_CORNER "\xee\x8d\xad"  // U+E36D
#define ICON_LUCIDE_FILE_UP "\xee\x8c\xaa"  // U+E32A
#define ICON_LUCIDE_FILE_USER "\xee\x98\xad"  // U+E62D
#define ICON_LUCIDE_FILE_VIDEO_CAMERA "\xee\x8c\xab"  // U+E32B
#define ICON_LUCIDE_FILE_VOLUME "\xee\x8c\xac"  // U+E32C
#define ICON_LUCIDE_FILE_X "\xee\x83\x8d"  // U+E0CD
#define ICON_LUCIDE_FILE_X_CORNER "\xee\x83\x8e"  // U+E0CE
#define ICON_LUCIDE_FILES "\xee\x83\x8f"  // U+E0CF
#define ICON_LUCIDE_FILM "\xee\x83\x90"  // U+E0D0
#define ICON_LUCIDE_FINGERPRINT_PATTERN "\xee\x8b\x8b"  // U+E2CB
#define ICON_LUCIDE_FIRE_EXTINGUISHER "\xee\x95\xbe"  // U+E57E
#define ICON_LUCIDE_FISH "\xee\x8e\xa6"  // U+E3A6
#define ICON_LUCIDE_FISH_OFF "\xee\x8e\xb0"  // U+E3B0
#define ICON_LUCIDE_FISH_SYMBOL "\xee\x93\xb4"  // U+E4F4
#define ICON_LUCIDE_FISHING_HOOK "\xee\x9a\xb6"  // U+E6B6
#define ICON_LUCIDE_FLAG "\xee\x83\x91"  // U+E0D1
#define ICON_LUCIDE_FLAG_OFF "\xee\x8a\x92"  // U+E292
#define ICON_LUCIDE_FLAG_TRIANGLE_LEFT "\xee\x88\xb7"  // U+E237
#define ICON_LUCIDE_FLAG_TRIANGLE_RIGHT "\xee\x88\xb8"  // U+E238
#define ICON_LUCIDE_FLAME "\xee\x83\x92"  // U+E0D2
#define ICON_LUCIDE_FLAME_KINDLING "\xee\x94\xba"  // U+E53A
#define ICON_LUCIDE_FLASHLIGHT "\xee\x83\x93"  // U+E0D3
#define ICON_LUCIDE_FLASHLIGHT_OFF "\xee\x83\x94"  // U+E0D4
#define ICON_LUCIDE_FLASK_CONICAL "\xee\x83\x95"  // U+E0D5
#define ICON_LUCIDE_FLASK_CONICAL_OFF "\xee\x8e\x96"  // U+E396
#define ICON_LUCIDE_FLASK_ROUND "\xee\x83\x96"  // U+E0D6
#define ICON_LUCIDE_FLIP_HORIZONTAL_2 "\xee\x8d\x9d"  // U+E35D
#define ICON_LUCIDE_FLIP_VERTICAL_2 "\xee\x8d\x9e"  // U+E35E
#define ICON_LUCIDE_FLOWER "\xee\x8b\x93"  // U+E2D3
#define ICON_LUCIDE_FLOWER_2 "\xee\x8b\x94"  // U+E2D4
#define ICON_LUCIDE_FOCUS "\xee\x8a\x9e"  // U+E29E
#define ICON_LUCIDE_FOLD_HORIZONTAL "\xee\x90\xbb"  // U+E43B
#define ICON_LUCIDE_FOLD_VERTICAL "\xee\x90\xbc"  // U+E43C
#define ICON_LUCIDE_FOLDER "\xee\x83\x97"  // U+E0D7
#define ICON_LUCIDE_FOLDER_ARCHIVE "\xee\x8c\xad"  // U+E32D
#define ICON_LUCIDE_FOLDER_CHECK "\xee\x8c\xae"  // U+E32E
#define ICON_LUCIDE_FOLDER_CLOCK "\xee\x8c\xaf"  // U+E32F
#define ICON_LUCIDE_FOLDER_CLOSED "\xee\x8c\xb0"  // U+E330
#define ICON_LUCIDE_FOLDER_CODE "\xee\x97\xbb"  // U+E5FB
#define ICON_LUCIDE_FOLDER_COG "\xee\x8c\xb1"  // U+E331
#define ICON_LUCIDE_FOLDER_DOT "\xee\x93\x85"  // U+E4C5
#define ICON_LUCIDE_FOLDER_DOWN "\xee\x8c\xb2"  // U+E332
#define ICON_LUCIDE_FOLDER_GIT "\xee\x90\x89"  // U+E409
#define ICON_LUCIDE_FOLDER_GIT_2 "\xee\x90\x8a"  // U+E40A
#define ICON_LUCIDE_FOLDER_HEART "\xee\x8c\xb3"  // U+E333
#define ICON_LUCIDE_FOLDER_INPUT "\xee\x8c\xb4"  // U+E334
#define ICON_LUCIDE_FOLDER_KANBAN "\xee\x93\x86"  // U+E4C6
#define ICON_LUCIDE_FOLDER_KEY "\xee\x8c\xb5"  // U+E335
#define ICON_LUCIDE_FOLDER_LOCK "\xee\x8c\xb6"  // U+E336
#define ICON_LUCIDE_FOLDER_MINUS "\xee\x83\x98"  // U+E0D8
#define ICON_LUCIDE_FOLDER_OPEN "\xee\x89\x87"  // U+E247
#define ICON_LUCIDE_FOLDER_OPEN_DOT "\xee\x93\x87"  // U+E4C7
#define ICON_LUCIDE_FOLDER_OUTPUT "\xee\x8c\xb7"  // U+E337
#define ICON_LUCIDE_FOLDER_PEN "\xee\x8c\xb8"  // U+E338
#define ICON_LUCIDE_FOLDER_PLUS "\xee\x83\x99"  // U+E0D9
#define ICON_LUCIDE_FOLDER_ROOT "\xee\x93\x88"  // U+E4C8
#define ICON_LUCIDE_FOLDER_SEARCH "\xee\x8c\xb9"  // U+E339
#define ICON_LUCIDE_FOLDER_SEARCH_2 "\xee\x8c\xba"  // U+E33A
#define ICON_LUCIDE_FOLDER_SYMLINK "\xee\x8c\xbb"  // U+E33B
#define ICON_LUCIDE_FOLDER_SYNC "\xee\x93\x89"  // U+E4C9
#define ICON_LUCIDE_FOLDER_TREE "\xee\x8c\xbc"  // U+E33C
#define ICON_LUCIDE_FOLDER_UP "\xee\x8c\xbd"  // U+E33D
#define ICON_LUCIDE_FOLDER_X "\xee\x8c\xbe"  // U+E33E
#define ICON_LUCIDE_FOLDERS "\xee\x8c\xbf"  // U+E33F
#define ICON_LUCIDE_FOOTPRINTS "\xee\x8e\xb9"  // U+E3B9
#define ICON_LUCIDE_FORKLIFT "\xee\x8f\x81"  // U+E3C1
#define ICON_LUCIDE_FORM "\xee\x9a\xa8"  // U+E6A8
#define ICON_LUCIDE_FORWARD "\xee\x88\xa9"  // U+E229
#define ICON_LUCIDE_FRAME "\xee\x8a\x91"  // U+E291
#define ICON_LUCIDE_FRAMER "\xee\x83\x9a"  // U+E0DA
#define ICON_LUCIDE_FROWN "\xee\x83\x9b"  // U+E0DB
#define ICON_LUCIDE_FUEL "\xee\x8a\xaf"  // U+E2AF
#define ICON_LUCIDE_FULLSCREEN "\xee\x94\xb4"  // U+E534
#define ICON_LUCIDE_FUNNEL "\xee\x83\x9c"  // U+E0DC
#define ICON_LUCIDE_FUNNEL_PLUS "\xee\x83\x9d"  // U+E0DD
#define ICON_LUCIDE_FUNNEL_X "\xee\x8e\xb5"  // U+E3B5
#define ICON_LUCIDE_GALLERY_HORIZONTAL "\xee\x93\x8e"  // U+E4CE
#define ICON_LUCIDE_GALLERY_HORIZONTAL_END "\xee\x93\x8f"  // U+E4CF
#define ICON_LUCIDE_GALLERY_THUMBNAILS "\xee\x93\x90"  // U+E4D0
#define ICON_LUCIDE_GALLERY_VERTICAL "\xee\x93\x91"  // U+E4D1
#define ICON_LUCIDE_GALLERY_VERTICAL_END "\xee\x93\x92"  // U+E4D2
#define ICON_LUCIDE_GAMEPAD "\xee\x83\x9e"  // U+E0DE
#define ICON_LUCIDE_GAMEPAD_2 "\xee\x83\x9f"  // U+E0DF
#define ICON_LUCIDE_GAMEPAD_DIRECTIONAL "\xee\x9a\x9b"  // U+E69B
#define ICON_LUCIDE_GAUGE "\xee\x86\xbf"  // U+E1BF
#define ICON_LUCIDE_GAVEL "\xee\x83\xa0"  // U+E0E0
#define ICON_LUCIDE_GEM "\xee\x89\x82"  // U+E242
#define ICON_LUCIDE_GEORGIAN_LARI "\xee\x99\xb8"  // U+E678
#define ICON_LUCIDE_GHOST "\xee\x88\x8e"  // U+E20E
#define ICON_LUCIDE_GIFT "\xee\x83\xa1"  // U+E0E1
#define ICON_LUCIDE_GIT_BRANCH "\xee\x83\xa2"  // U+E0E2
#define ICON_LUCIDE_GIT_BRANCH_MINUS "\xee\x9a\x9c"  // U+E69C
#define ICON_LUCIDE_GIT_BRANCH_PLUS "\xee\x87\xb4"  // U+E1F4
#define ICON_LUCIDE_GIT_COMMIT_HORIZONTAL "\xee\x83\xa3"  // U+E0E3
#define ICON_LUCIDE_GIT_COMMIT_VERTICAL "\xee\x95\x92"  // U+E552
#define ICON_LUCIDE_GIT_COMPARE "\xee\x8d\x99"  // U+E359
#define ICON_LUCIDE_GIT_COMPARE_ARROWS "\xee\x95\x93"  // U+E553
#define ICON_LUCIDE_GIT_FORK "\xee\x8a\x8d"  // U+E28D
#define ICON_LUCIDE_GIT_GRAPH "\xee\x95\x94"  // U+E554
#define ICON_LUCIDE_GIT_MERGE "\xee\x83\xa4"  // U+E0E4
#define ICON_LUCIDE_GIT_MERGE_CONFLICT "\xee\x9b\x83"  // U+E6C3
#define ICON_LUCIDE_GIT_PULL_REQUEST "\xee\x83\xa5"  // U+E0E5
#define ICON_LUCIDE_GIT_PULL_REQUEST_ARROW "\xee\x95\x95"  // U+E555
#define ICON_LUCIDE_GIT_PULL_REQUEST_CLOSED "\xee\x8d\x9a"  // U+E35A
#define ICON_LUCIDE_GIT_PULL_REQUEST_CREATE "\xee\x95\x96"  // U+E556
#define ICON_LUCIDE_GIT_PULL_REQUEST_CREATE_ARROW "\xee\x95\x97"  // U+E557
#define ICON_LUCIDE_GIT_PULL_REQUEST_DRAFT "\xee\x8d\x9b"  // U+E35B
#define ICON_LUCIDE_GITHUB "\xee\x83\xa6"  // U+E0E6
#define ICON_LUCIDE_GITLAB "\xee\x83\xa7"  // U+E0E7
#define ICON_LUCIDE_GLASS_WATER "\xee\x8b\x95"  // U+E2D5
#define ICON_LUCIDE_GLASSES "\xee\x88\x8d"  // U+E20D
#define ICON_LUCIDE_GLOBE "\xee\x83\xa8"  // U+E0E8
#define ICON_LUCIDE_GLOBE_LOCK "\xee\x97\x8d"  // U+E5CD
#define ICON_LUCIDE_GLOBE_OFF "\xee\x9b\x81"  // U+E6C1
#define ICON_LUCIDE_GLOBE_X "\xee\x9a\xba"  // U+E6BA
#define ICON_LUCIDE_GOAL "\xee\x92\xa5"  // U+E4A5
#define ICON_LUCIDE_GPU "\xee\x99\xaa"  // U+E66A
#define ICON_LUCIDE_GRADUATION_CAP "\xee\x88\xb4"  // U+E234
#define ICON_LUCIDE_GRAPE "\xee\x8d\x92"  // U+E352
#define ICON_LUCIDE_GRID_2X2 "\xee\x93\xbf"  // U+E4FF
#define ICON_LUCIDE_GRID_2X2_CHECK "\xee\x97\xa4"  // U+E5E4
#define ICON_LUCIDE_GRID_2X2_PLUS "\xee\x98\xa8"  // U+E628
#define ICON_LUCIDE_GRID_2X2_X "\xee\x97\xa5"  // U+E5E5
#define ICON_LUCIDE_GRID_3X2 "\xee\x99\xaf"  // U+E66F
#define ICON_LUCIDE_GRID_3X3 "\xee\x83\xa9"  // U+E0E9
#define ICON_LUCIDE_GRIP "\xee\x8e\xb1"  // U+E3B1
#define ICON_LUCIDE_GRIP_HORIZONTAL "\xee\x83\xaa"  // U+E0EA
#define ICON_LUCIDE_GRIP_VERTICAL "\xee\x83\xab"  // U+E0EB
#define ICON_LUCIDE_GROUP "\xee\x91\xa4"  // U+E464
#define ICON_LUCIDE_GUITAR "\xee\x95\x9f"  // U+E55F
#define ICON_LUCIDE_HAM "\xee\x97\x97"  // U+E5D7
#define ICON_LUCIDE_HAMBURGER "\xee\x99\xa5"  // U+E665
#define ICON_LUCIDE_HAMMER "\xee\x83\xac"  // U+E0EC
#define ICON_LUCIDE_HAND "\xee\x87\x97"  // U+E1D7
#define ICON_LUCIDE_HAND_COINS "\xee\x96\xb8"  // U+E5B8
#define ICON_LUCIDE_HAND_FIST "\xee\x9a\x8b"  // U+E68B
#define ICON_LUCIDE_HAND_GRAB "\xee\x87\xa6"  // U+E1E6
#define ICON_LUCIDE_HAND_HEART "\xee\x96\xb9"  // U+E5B9
#define ICON_LUCIDE_HAND_HELPING "\xee\x8e\xb8"  // U+E3B8
#define ICON_LUCIDE_HAND_METAL "\xee\x88\xac"  // U+E22C
#define ICON_LUCIDE_HAND_PLATTER "\xee\x96\xba"  // U+E5BA
#define ICON_LUCIDE_HANDBAG "\xee\x9a\x89"  // U+E689
#define ICON_LUCIDE_HANDSHAKE "\xee\x97\x80"  // U+E5C0
#define ICON_LUCIDE_HARD_DRIVE "\xee\x83\xad"  // U+E0ED
#define ICON_LUCIDE_HARD_DRIVE_DOWNLOAD "\xee\x93\xa5"  // U+E4E5
#define ICON_LUCIDE_HARD_DRIVE_UPLOAD "\xee\x93\xa6"  // U+E4E6
#define ICON_LUCIDE_HARD_HAT "\xee\x83\xae"  // U+E0EE
#define ICON_LUCIDE_HASH "\xee\x83\xaf"  // U+E0EF
#define ICON_LUCIDE_HAT_GLASSES "\xee\x9a\x83"  // U+E683
#define ICON_LUCIDE_HAZE "\xee\x83\xb0"  // U+E0F0
#define ICON_LUCIDE_HD "\xee\x9a\xb5"  // U+E6B5
#define ICON_LUCIDE_HDMI_PORT "\xee\x93\xa7"  // U+E4E7
#define ICON_LUCIDE_HEADING "\xee\x8e\x84"  // U+E384
#define ICON_LUCIDE_HEADING_1 "\xee\x8e\x85"  // U+E385
#define ICON_LUCIDE_HEADING_2 "\xee\x8e\x86"  // U+E386
#define ICON_LUCIDE_HEADING_3 "\xee\x8e\x87"  // U+E387
#define ICON_LUCIDE_HEADING_4 "\xee\x8e\x88"  // U+E388
#define ICON_LUCIDE_HEADING_5 "\xee\x8e\x89"  // U+E389
#define ICON_LUCIDE_HEADING_6 "\xee\x8e\x8a"  // U+E38A
#define ICON_LUCIDE_HEADPHONE_OFF "\xee\x98\xa9"  // U+E629
#define ICON_LUCIDE_HEADPHONES "\xee\x83\xb1"  // U+E0F1
#define ICON_LUCIDE_HEADSET "\xee\x96\xbd"  // U+E5BD
#define ICON_LUCIDE_HEART "\xee\x83\xb2"  // U+E0F2
#define ICON_LUCIDE_HEART_CRACK "\xee\x8b\x96"  // U+E2D6
#define ICON_LUCIDE_HEART_HANDSHAKE "\xee\x8b\x97"  // U+E2D7
#define ICON_LUCIDE_HEART_MINUS "\xee\x99\x91"  // U+E651
#define ICON_LUCIDE_HEART_OFF "\xee\x8a\x95"  // U+E295
#define ICON_LUCIDE_HEART_PLUS "\xee\x99\x92"  // U+E652
#define ICON_LUCIDE_HEART_PULSE "\xee\x8d\xae"  // U+E36E
#define ICON_LUCIDE_HEATER "\xee\x96\x8e"  // U+E58E
#define ICON_LUCIDE_HELICOPTER "\xee\x9a\x9d"  // U+E69D
#define ICON_LUCIDE_HEXAGON "\xee\x83\xb3"  // U+E0F3
#define ICON_LUCIDE_HIGHLIGHTER "\xee\x83\xb4"  // U+E0F4
#define ICON_LUCIDE_HISTORY "\xee\x87\xb5"  // U+E1F5
#define ICON_LUCIDE_HOP "\xee\x8e\x97"  // U+E397
#define ICON_LUCIDE_HOP_OFF "\xee\x8e\x98"  // U+E398
#define ICON_LUCIDE_HOSPITAL "\xee\x97\x98"  // U+E5D8
#define ICON_LUCIDE_HOTEL "\xee\x8f\xa2"  // U+E3E2
#define ICON_LUCIDE_HOURGLASS "\xee\x8a\x96"  // U+E296
#define ICON_LUCIDE_HOUSE "\xee\x83\xb5"  // U+E0F5
#define ICON_LUCIDE_HOUSE_HEART "\xee\x9a\x95"  // U+E695
#define ICON_LUCIDE_HOUSE_PLUG "\xee\x97\xb0"  // U+E5F0
#define ICON_LUCIDE_HOUSE_PLUS "\xee\x97\xb1"  // U+E5F1
#define ICON_LUCIDE_HOUSE_WIFI "\xee\x98\xbc"  // U+E63C
#define ICON_LUCIDE_ICE_CREAM_BOWL "\xee\x8e\xa7"  // U+E3A7
#define ICON_LUCIDE_ICE_CREAM_CONE "\xee\x8d\x93"  // U+E353
#define ICON_LUCIDE_ID_CARD "\xee\x98\x97"  // U+E617
#define ICON_LUCIDE_ID_CARD_LANYARD "\xee\x99\xb0"  // U+E670
#define ICON_LUCIDE_IMAGE "\xee\x83\xb6"  // U+E0F6
#define ICON_LUCIDE_IMAGE_DOWN "\xee\x94\xbc"  // U+E53C
#define ICON_LUCIDE_IMAGE_MINUS "\xee\x87\xb6"  // U+E1F6
#define ICON_LUCIDE_IMAGE_OFF "\xee\x87\x80"  // U+E1C0
#define ICON_LUCIDE_IMAGE_PLAY "\xee\x97\x9f"  // U+E5DF
#define ICON_LUCIDE_IMAGE_PLUS "\xee\x87\xb7"  // U+E1F7
#define ICON_LUCIDE_IMAGE_UP "\xee\x97\x8b"  // U+E5CB
#define ICON_LUCIDE_IMAGE_UPSCALE "\xee\x98\xb7"  // U+E637
#define ICON_LUCIDE_IMAGES "\xee\x97\x84"  // U+E5C4
#define ICON_LUCIDE_IMPORT "\xee\x88\xaf"  // U+E22F
#define ICON_LUCIDE_INBOX "\xee\x83\xb7"  // U+E0F7
#define ICON_LUCIDE_INDIAN_RUPEE "\xee\x83\xb8"  // U+E0F8
#define ICON_LUCIDE_INFINITY "\xee\x87\xa7"  // U+E1E7
#define ICON_LUCIDE_INFO "\xee\x83\xb9"  // U+E0F9
#define ICON_LUCIDE_INSPECTION_PANEL "\xee\x96\x83"  // U+E583
#define ICON_LUCIDE_INSTAGRAM "\xee\x83\xba"  // U+E0FA
#define ICON_LUCIDE_ITALIC "\xee\x83\xbb"  // U+E0FB
#define ICON_LUCIDE_ITERATION_CCW "\xee\x90\xa3"  // U+E423
#define ICON_LUCIDE_ITERATION_CW "\xee\x90\xa4"  // U+E424
#define ICON_LUCIDE_JAPANESE_YEN "\xee\x83\xbc"  // U+E0FC
#define ICON_LUCIDE_JOYSTICK "\xee\x8d\x95"  // U+E355
#define ICON_LUCIDE_KANBAN "\xee\x93\x9c"  // U+E4DC
#define ICON_LUCIDE_KAYAK "\xee\x9a\x8f"  // U+E68F
#define ICON_LUCIDE_KEY "\xee\x83\xbd"  // U+E0FD
#define ICON_LUCIDE_KEY_ROUND "\xee\x92\xa3"  // U+E4A3
#define ICON_LUCIDE_KEY_SQUARE "\xee\x92\xa4"  // U+E4A4
#define ICON_LUCIDE_KEYBOARD "\xee\x8a\x84"  // U+E284
#define ICON_LUCIDE_KEYBOARD_MUSIC "\xee\x95\xa0"  // U+E560
#define ICON_LUCIDE_KEYBOARD_OFF "\xee\x97\x9e"  // U+E5DE
#define ICON_LUCIDE_LAMP "\xee\x8b\x98"  // U+E2D8
#define ICON_LUCIDE_LAMP_CEILING "\xee\x8b\x99"  // U+E2D9
#define ICON_LUCIDE_LAMP_DESK "\xee\x8b\x9a"  // U+E2DA
#define ICON_LUCIDE_LAMP_FLOOR "\xee\x8b\x9b"  // U+E2DB
#define ICON_LUCIDE_LAMP_WALL_DOWN "\xee\x8b\x9c"  // U+E2DC
#define ICON_LUCIDE_LAMP_WALL_UP "\xee\x8b\x9d"  // U+E2DD
#define ICON_LUCIDE_LAND_PLOT "\xee\x94\xa8"  // U+E528
#define ICON_LUCIDE_LANDMARK "\xee\x88\xba"  // U+E23A
#define ICON_LUCIDE_LANGUAGES "\xee\x83\xbe"  // U+E0FE
#define ICON_LUCIDE_LAPTOP "\xee\x87\x8d"  // U+E1CD
#define ICON_LUCIDE_LAPTOP_MINIMAL "\xee\x87\x98"  // U+E1D8
#define ICON_LUCIDE_LAPTOP_MINIMAL_CHECK "\xee\x98\xb2"  // U+E632
#define ICON_LUCIDE_LASSO "\xee\x87\x8e"  // U+E1CE
#define ICON_LUCIDE_LASSO_SELECT "\xee\x87\x8f"  // U+E1CF
#define ICON_LUCIDE_LAUGH "\xee\x8c\x80"  // U+E300
#define ICON_LUCIDE_LAYERS "\xee\x94\xa9"  // U+E529
#define ICON_LUCIDE_LAYERS_2 "\xee\x94\xaa"  // U+E52A
#define ICON_LUCIDE_LAYERS_PLUS "\xee\x9a\xb3"  // U+E6B3
#define ICON_LUCIDE_LAYOUT_DASHBOARD "\xee\x87\x81"  // U+E1C1
#define ICON_LUCIDE_LAYOUT_GRID "\xee\x83\xbf"  // U+E0FF
#define ICON_LUCIDE_LAYOUT_LIST "\xee\x87\x99"  // U+E1D9
#define ICON_LUCIDE_LAYOUT_PANEL_LEFT "\xee\x91\xb0"  // U+E470
#define ICON_LUCIDE_LAYOUT_PANEL_TOP "\xee\x91\xb1"  // U+E471
#define ICON_LUCIDE_LAYOUT_TEMPLATE "\xee\x88\x87"  // U+E207
#define ICON_LUCIDE_LEAF "\xee\x8b\x9e"  // U+E2DE
#define ICON_LUCIDE_LEAFY_GREEN "\xee\x91\xaf"  // U+E46F
#define ICON_LUCIDE_LECTERN "\xee\x97\xa9"  // U+E5E9
#define ICON_LUCIDE_LENS_CONCAVE "\xee\x9a\xbf"  // U+E6BF
#define ICON_LUCIDE_LENS_CONVEX "\xee\x9b\x80"  // U+E6C0
#define ICON_LUCIDE_LIBRARY "\xee\x84\x80"  // U+E100
#define ICON_LUCIDE_LIBRARY_BIG "\xee\x95\x8e"  // U+E54E
#define ICON_LUCIDE_LIFE_BUOY "\xee\x84\x81"  // U+E101
#define ICON_LUCIDE_LIGATURE "\xee\x90\xba"  // U+E43A
#define ICON_LUCIDE_LIGHTBULB "\xee\x87\x82"  // U+E1C2
#define ICON_LUCIDE_LIGHTBULB_OFF "\xee\x88\x88"  // U+E208
#define ICON_LUCIDE_LINE_DOT_RIGHT_HORIZONTAL "\xee\x9b\x82"  // U+E6C2
#define ICON_LUCIDE_LINE_SQUIGGLE "\xee\x99\xba"  // U+E67A
#define ICON_LUCIDE_LINK "\xee\x84\x82"  // U+E102
#define ICON_LUCIDE_LINK_2 "\xee\x84\x83"  // U+E103
#define ICON_LUCIDE_LINK_2_OFF "\xee\x84\x84"  // U+E104
#define ICON_LUCIDE_LINKEDIN "\xee\x84\x85"  // U+E105
#define ICON_LUCIDE_LIST "\xee\x84\x86"  // U+E106
#define ICON_LUCIDE_LIST_CHECK "\xee\x97\xba"  // U+E5FA
#define ICON_LUCIDE_LIST_CHECKS "\xee\x87\x90"  // U+E1D0
#define ICON_LUCIDE_LIST_CHEVRONS_DOWN_UP "\xee\x9a\x94"  // U+E694
#define ICON_LUCIDE_LIST_CHEVRONS_UP_DOWN "\xee\x9a\x96"  // U+E696
#define ICON_LUCIDE_LIST_COLLAPSE "\xee\x96\x9b"  // U+E59B
#define ICON_LUCIDE_LIST_END "\xee\x8b\x9f"  // U+E2DF
#define ICON_LUCIDE_LIST_FILTER "\xee\x91\xa0"  // U+E460
#define ICON_LUCIDE_LIST_FILTER_PLUS "\xee\x98\xb9"  // U+E639
#define ICON_LUCIDE_LIST_INDENT_DECREASE "\xee\x84\x87"  // U+E107
#define ICON_LUCIDE_LIST_INDENT_INCREASE "\xee\x84\x88"  // U+E108
#define ICON_LUCIDE_LIST_MINUS "\xee\x88\xbe"  // U+E23E
#define ICON_LUCIDE_LIST_MUSIC "\xee\x8b\xa0"  // U+E2E0
#define ICON_LUCIDE_LIST_ORDERED "\xee\x87\x91"  // U+E1D1
#define ICON_LUCIDE_LIST_PLUS "\xee\x88\xbf"  // U+E23F
#define ICON_LUCIDE_LIST_RESTART "\xee\x91\x92"  // U+E452
#define ICON_LUCIDE_LIST_START "\xee\x8b\xa1"  // U+E2E1
#define ICON_LUCIDE_LIST_TODO "\xee\x93\x83"  // U+E4C3
#define ICON_LUCIDE_LIST_TREE "\xee\x90\x88"  // U+E408
#define ICON_LUCIDE_LIST_VIDEO "\xee\x8b\xa2"  // U+E2E2
#define ICON_LUCIDE_LIST_X "\xee\x89\x80"  // U+E240
#define ICON_LUCIDE_LOADER "\xee\x84\x89"  // U+E109
#define ICON_LUCIDE_LOADER_CIRCLE "\xee\x84\x8a"  // U+E10A
#define ICON_LUCIDE_LOADER_PINWHEEL "\xee\x97\xa6"  // U+E5E6
#define ICON_LUCIDE_LOCATE "\xee\x87\x9a"  // U+E1DA
#define ICON_LUCIDE_LOCATE_FIXED "\xee\x87\x9b"  // U+E1DB
#define ICON_LUCIDE_LOCATE_OFF "\xee\x8a\x82"  // U+E282
#define ICON_LUCIDE_LOCK "\xee\x84\x8b"  // U+E10B
#define ICON_LUCIDE_LOCK_KEYHOLE "\xee\x94\xb1"  // U+E531
#define ICON_LUCIDE_LOCK_KEYHOLE_OPEN "\xee\x94\xb2"  // U+E532
#define ICON_LUCIDE_LOCK_OPEN "\xee\x84\x8c"  // U+E10C
#define ICON_LUCIDE_LOG_IN "\xee\x84\x8d"  // U+E10D
#define ICON_LUCIDE_LOG_OUT "\xee\x84\x8e"  // U+E10E
#define ICON_LUCIDE_LOGS "\xee\x97\xb4"  // U+E5F4
#define ICON_LUCIDE_LOLLIPOP "\xee\x92\xbd"  // U+E4BD
#define ICON_LUCIDE_LUGGAGE "\xee\x8b\x8a"  // U+E2CA
#define ICON_LUCIDE_MAGNET "\xee\x8a\xb5"  // U+E2B5
#define ICON_LUCIDE_MAIL "\xee\x84\x8f"  // U+E10F
#define ICON_LUCIDE_MAIL_CHECK "\xee\x8d\xa1"  // U+E361
#define ICON_LUCIDE_MAIL_MINUS "\xee\x8d\xa2"  // U+E362
#define ICON_LUCIDE_MAIL_OPEN "\xee\x8d\xa3"  // U+E363
#define ICON_LUCIDE_MAIL_PLUS "\xee\x8d\xa4"  // U+E364
#define ICON_LUCIDE_MAIL_QUESTION_MARK "\xee\x8d\xa5"  // U+E365
#define ICON_LUCIDE_MAIL_SEARCH "\xee\x8d\xa6"  // U+E366
#define ICON_LUCIDE_MAIL_WARNING "\xee\x8d\xa7"  // U+E367
#define ICON_LUCIDE_MAIL_X "\xee\x8d\xa8"  // U+E368
#define ICON_LUCIDE_MAILBOX "\xee\x8f\x94"  // U+E3D4
#define ICON_LUCIDE_MAILS "\xee\x8d\xa9"  // U+E369
#define ICON_LUCIDE_MAP "\xee\x84\x90"  // U+E110
#define ICON_LUCIDE_MAP_MINUS "\xee\x9a\x86"  // U+E686
#define ICON_LUCIDE_MAP_PIN "\xee\x84\x91"  // U+E111
#define ICON_LUCIDE_MAP_PIN_CHECK "\xee\x98\x8f"  // U+E60F
#define ICON_LUCIDE_MAP_PIN_CHECK_INSIDE "\xee\x98\x90"  // U+E610
#define ICON_LUCIDE_MAP_PIN_HOUSE "\xee\x98\x9c"  // U+E61C
#define ICON_LUCIDE_MAP_PIN_MINUS "\xee\x98\x91"  // U+E611
#define ICON_LUCIDE_MAP_PIN_MINUS_INSIDE "\xee\x98\x92"  // U+E612
#define ICON_LUCIDE_MAP_PIN_OFF "\xee\x8a\xa6"  // U+E2A6
#define ICON_LUCIDE_MAP_PIN_PEN "\xee\x99\x95"  // U+E655
#define ICON_LUCIDE_MAP_PIN_PLUS "\xee\x98\x93"  // U+E613
#define ICON_LUCIDE_MAP_PIN_PLUS_INSIDE "\xee\x98\x94"  // U+E614
#define ICON_LUCIDE_MAP_PIN_X "\xee\x98\x95"  // U+E615
#define ICON_LUCIDE_MAP_PIN_X_INSIDE "\xee\x98\x96"  // U+E616
#define ICON_LUCIDE_MAP_PINNED "\xee\x94\xbd"  // U+E53D
#define ICON_LUCIDE_MAP_PLUS "\xee\x98\xbf"  // U+E63F
#define ICON_LUCIDE_MARS "\xee\x99\x81"  // U+E641
#define ICON_LUCIDE_MARS_STROKE "\xee\x99\x82"  // U+E642
#define ICON_LUCIDE_MARTINI "\xee\x8b\xa3"  // U+E2E3
#define ICON_LUCIDE_MAXIMIZE "\xee\x84\x92"  // U+E112
#define ICON_LUCIDE_MAXIMIZE_2 "\xee\x84\x93"  // U+E113
#define ICON_LUCIDE_MEDAL "\xee\x8d\xaf"  // U+E36F
#define ICON_LUCIDE_MEGAPHONE "\xee\x88\xb5"  // U+E235
#define ICON_LUCIDE_MEGAPHONE_OFF "\xee\x8d\xb0"  // U+E370
#define ICON_LUCIDE_MEH "\xee\x84\x94"  // U+E114
#define ICON_LUCIDE_MEMORY_STICK "\xee\x91\x85"  // U+E445
#define ICON_LUCIDE_MENU "\xee\x84\x95"  // U+E115
#define ICON_LUCIDE_MERGE "\xee\x90\xbf"  // U+E43F
#define ICON_LUCIDE_MESSAGE_CIRCLE "\xee\x84\x96"  // U+E116
#define ICON_LUCIDE_MESSAGE_CIRCLE_CHECK "\xee\x9b\x88"  // U+E6C8
#define ICON_LUCIDE_MESSAGE_CIRCLE_CODE "\xee\x95\xa2"  // U+E562
#define ICON_LUCIDE_MESSAGE_CIRCLE_DASHED "\xee\x95\xa3"  // U+E563
#define ICON_LUCIDE_MESSAGE_CIRCLE_HEART "\xee\x95\xa4"  // U+E564
#define ICON_LUCIDE_MESSAGE_CIRCLE_MORE "\xee\x95\xa5"  // U+E565
#define ICON_LUCIDE_MESSAGE_CIRCLE_OFF "\xee\x95\xa6"  // U+E566
#define ICON_LUCIDE_MESSAGE_CIRCLE_PLUS "\xee\x95\xa7"  // U+E567
#define ICON_LUCIDE_MESSAGE_CIRCLE_QUESTION_MARK "\xee\x95\xa8"  // U+E568
#define ICON_LUCIDE_MESSAGE_CIRCLE_REPLY "\xee\x95\xa9"  // U+E569
#define ICON_LUCIDE_MESSAGE_CIRCLE_WARNING "\xee\x95\xaa"  // U+E56A
#define ICON_LUCIDE_MESSAGE_CIRCLE_X "\xee\x95\xab"  // U+E56B
#define ICON_LUCIDE_MESSAGE_SQUARE "\xee\x84\x97"  // U+E117
#define ICON_LUCIDE_MESSAGE_SQUARE_CHECK "\xee\x9b\x8c"  // U+E6CC
#define ICON_LUCIDE_MESSAGE_SQUARE_CODE "\xee\x95\xac"  // U+E56C
#define ICON_LUCIDE_MESSAGE_SQUARE_DASHED "\xee\x90\x8b"  // U+E40B
#define ICON_LUCIDE_MESSAGE_SQUARE_DIFF "\xee\x95\xad"  // U+E56D
#define ICON_LUCIDE_MESSAGE_SQUARE_DOT "\xee\x95\xae"  // U+E56E
#define ICON_LUCIDE_MESSAGE_SQUARE_HEART "\xee\x95\xaf"  // U+E56F
#define ICON_LUCIDE_MESSAGE_SQUARE_LOCK "\xee\x98\xac"  // U+E62C
#define ICON_LUCIDE_MESSAGE_SQUARE_MORE "\xee\x95\xb0"  // U+E570
#define ICON_LUCIDE_MESSAGE_SQUARE_OFF "\xee\x95\xb1"  // U+E571
#define ICON_LUCIDE_MESSAGE_SQUARE_PLUS "\xee\x90\x8c"  // U+E40C
#define ICON_LUCIDE_MESSAGE_SQUARE_QUOTE "\xee\x95\xb2"  // U+E572
#define ICON_LUCIDE_MESSAGE_SQUARE_REPLY "\xee\x95\xb3"  // U+E573
#define ICON_LUCIDE_MESSAGE_SQUARE_SHARE "\xee\x95\xb4"  // U+E574
#define ICON_LUCIDE_MESSAGE_SQUARE_TEXT "\xee\x95\xb5"  // U+E575
#define ICON_LUCIDE_MESSAGE_SQUARE_WARNING "\xee\x95\xb6"  // U+E576
#define ICON_LUCIDE_MESSAGE_SQUARE_X "\xee\x95\xb7"  // U+E577
#define ICON_LUCIDE_MESSAGES_SQUARE "\xee\x90\x8d"  // U+E40D
#define ICON_LUCIDE_METRONOME "\xee\x9b\x8d"  // U+E6CD
#define ICON_LUCIDE_MIC "\xee\x84\x98"  // U+E118
#define ICON_LUCIDE_MIC_OFF "\xee\x84\x99"  // U+E119
#define ICON_LUCIDE_MIC_VOCAL "\xee\x8d\x89"  // U+E349
#define ICON_LUCIDE_MICROCHIP "\xee\x98\x9a"  // U+E61A
#define ICON_LUCIDE_MICROSCOPE "\xee\x8b\xa4"  // U+E2E4
#define ICON_LUCIDE_MICROWAVE "\xee\x8d\xba"  // U+E37A
#define ICON_LUCIDE_MILESTONE "\xee\x8a\x98"  // U+E298
#define ICON_LUCIDE_MILK "\xee\x8e\x99"  // U+E399
#define ICON_LUCIDE_MILK_OFF "\xee\x8e\x9a"  // U+E39A
#define ICON_LUCIDE_MINIMIZE "\xee\x84\x9a"  // U+E11A
#define ICON_LUCIDE_MINIMIZE_2 "\xee\x84\x9b"  // U+E11B
#define ICON_LUCIDE_MINUS "\xee\x84\x9c"  // U+E11C
#define ICON_LUCIDE_MIRROR_RECTANGULAR "\xee\x9b\x84"  // U+E6C4
#define ICON_LUCIDE_MIRROR_ROUND "\xee\x9b\x85"  // U+E6C5
#define ICON_LUCIDE_MONITOR "\xee\x84\x9d"  // U+E11D
#define ICON_LUCIDE_MONITOR_CHECK "\xee\x92\x82"  // U+E482
#define ICON_LUCIDE_MONITOR_CLOUD "\xee\x9a\x99"  // U+E699
#define ICON_LUCIDE_MONITOR_COG "\xee\x98\x83"  // U+E603
#define ICON_LUCIDE_MONITOR_DOT "\xee\x92\x83"  // U+E483
#define ICON_LUCIDE_MONITOR_DOWN "\xee\x90\xa1"  // U+E421
#define ICON_LUCIDE_MONITOR_OFF "\xee\x87\x9c"  // U+E1DC
#define ICON_LUCIDE_MONITOR_PAUSE "\xee\x92\x84"  // U+E484
#define ICON_LUCIDE_MONITOR_PLAY "\xee\x92\x85"  // U+E485
#define ICON_LUCIDE_MONITOR_SMARTPHONE "\xee\x8e\xa2"  // U+E3A2
#define ICON_LUCIDE_MONITOR_SPEAKER "\xee\x88\x90"  // U+E210
#define ICON_LUCIDE_MONITOR_STOP "\xee\x92\x86"  // U+E486
#define ICON_LUCIDE_MONITOR_UP "\xee\x90\xa2"  // U+E422
#define ICON_LUCIDE_MONITOR_X "\xee\x92\x87"  // U+E487
#define ICON_LUCIDE_MOON "\xee\x84\x9e"  // U+E11E
#define ICON_LUCIDE_MOON_STAR "\xee\x90\x90"  // U+E410
#define ICON_LUCIDE_MOTORBIKE "\xee\x9a\x98"  // U+E698
#define ICON_LUCIDE_MOUNTAIN "\xee\x88\xb1"  // U+E231
#define ICON_LUCIDE_MOUNTAIN_SNOW "\xee\x88\xb2"  // U+E232
#define ICON_LUCIDE_MOUSE "\xee\x8a\x8e"  // U+E28E
#define ICON_LUCIDE_MOUSE_LEFT "\xee\x9b\x89"  // U+E6C9
#define ICON_LUCIDE_MOUSE_OFF "\xee\x97\x9b"  // U+E5DB
#define ICON_LUCIDE_MOUSE_POINTER "\xee\x84\x9f"  // U+E11F
#define ICON_LUCIDE_MOUSE_POINTER_2 "\xee\x87\x83"  // U+E1C3
#define ICON_LUCIDE_MOUSE_POINTER_2_OFF "\xee\x9a\xa6"  // U+E6A6
#define ICON_LUCIDE_MOUSE_POINTER_BAN "\xee\x97\xa7"  // U+E5E7
#define ICON_LUCIDE_MOUSE_POINTER_CLICK "\xee\x84\xa0"  // U+E120
#define ICON_LUCIDE_MOUSE_RIGHT "\xee\x9b\x8a"  // U+E6CA
#define ICON_LUCIDE_MOVE "\xee\x84\xa1"  // U+E121
#define ICON_LUCIDE_MOVE_3D "\xee\x8b\xa5"  // U+E2E5
#define ICON_LUCIDE_MOVE_DIAGONAL "\xee\x87\x84"  // U+E1C4
#define ICON_LUCIDE_MOVE_DIAGONAL_2 "\xee\x87\x85"  // U+E1C5
#define ICON_LUCIDE_MOVE_DOWN "\xee\x92\x8c"  // U+E48C
#define ICON_LUCIDE_MOVE_DOWN_LEFT "\xee\x92\x8d"  // U+E48D
#define ICON_LUCIDE_MOVE_DOWN_RIGHT "\xee\x92\x8e"  // U+E48E
#define ICON_LUCIDE_MOVE_HORIZONTAL "\xee\x87\x86"  // U+E1C6
#define ICON_LUCIDE_MOVE_LEFT "\xee\x92\x8f"  // U+E48F
#define ICON_LUCIDE_MOVE_RIGHT "\xee\x92\x90"  // U+E490
#define ICON_LUCIDE_MOVE_UP "\xee\x92\x91"  // U+E491
#define ICON_LUCIDE_MOVE_UP_LEFT "\xee\x92\x92"  // U+E492
#define ICON_LUCIDE_MOVE_UP_RIGHT "\xee\x92\x93"  // U+E493
#define ICON_LUCIDE_MOVE_VERTICAL "\xee\x87\x87"  // U+E1C7
#define ICON_LUCIDE_MUSIC "\xee\x84\xa2"  // U+E122
#define ICON_LUCIDE_MUSIC_2 "\xee\x8d\x8a"  // U+E34A
#define ICON_LUCIDE_MUSIC_3 "\xee\x8d\x8b"  // U+E34B
#define ICON_LUCIDE_MUSIC_4 "\xee\x8d\x8c"  // U+E34C
#define ICON_LUCIDE_NAVIGATION "\xee\x84\xa3"  // U+E123
#define ICON_LUCIDE_NAVIGATION_2 "\xee\x84\xa4"  // U+E124
#define ICON_LUCIDE_NAVIGATION_2_OFF "\xee\x8a\xa7"  // U+E2A7
#define ICON_LUCIDE_NAVIGATION_OFF "\xee\x8a\xa8"  // U+E2A8
#define ICON_LUCIDE_NETWORK "\xee\x84\xa5"  // U+E125
#define ICON_LUCIDE_NEWSPAPER "\xee\x8d\x88"  // U+E348
#define ICON_LUCIDE_NFC "\xee\x8f\x83"  // U+E3C3
#define ICON_LUCIDE_NON_BINARY "\xee\x99\x83"  // U+E643
#define ICON_LUCIDE_NOTEBOOK "\xee\x96\x95"  // U+E595
#define ICON_LUCIDE_NOTEBOOK_PEN "\xee\x96\x96"  // U+E596
#define ICON_LUCIDE_NOTEBOOK_TABS "\xee\x96\x97"  // U+E597
#define ICON_LUCIDE_NOTEBOOK_TEXT "\xee\x96\x98"  // U+E598
#define ICON_LUCIDE_NOTEPAD_TEXT "\xee\x96\x99"  // U+E599
#define ICON_LUCIDE_NOTEPAD_TEXT_DASHED "\xee\x96\x9a"  // U+E59A
#define ICON_LUCIDE_NUT "\xee\x8e\x9b"  // U+E39B
#define ICON_LUCIDE_NUT_OFF "\xee\x8e\x9c"  // U+E39C
#define ICON_LUCIDE_OCTAGON "\xee\x84\xa6"  // U+E126
#define ICON_LUCIDE_OCTAGON_ALERT "\xee\x84\xa7"  // U+E127
#define ICON_LUCIDE_OCTAGON_MINUS "\xee\x98\xa7"  // U+E627
#define ICON_LUCIDE_OCTAGON_PAUSE "\xee\x88\x9b"  // U+E21B
#define ICON_LUCIDE_OCTAGON_X "\xee\x84\xa8"  // U+E128
#define ICON_LUCIDE_OMEGA "\xee\x98\x99"  // U+E619
#define ICON_LUCIDE_OPTION "\xee\x87\xb8"  // U+E1F8
#define ICON_LUCIDE_ORBIT "\xee\x8f\xa7"  // U+E3E7
#define ICON_LUCIDE_ORIGAMI "\xee\x97\xa3"  // U+E5E3
#define ICON_LUCIDE_PACKAGE "\xee\x84\xa9"  // U+E129
#define ICON_LUCIDE_PACKAGE_2 "\xee\x8d\x80"  // U+E340
#define ICON_LUCIDE_PACKAGE_CHECK "\xee\x89\xa6"  // U+E266
#define ICON_LUCIDE_PACKAGE_MINUS "\xee\x89\xa7"  // U+E267
#define ICON_LUCIDE_PACKAGE_OPEN "\xee\x8b\x8c"  // U+E2CC
#define ICON_LUCIDE_PACKAGE_PLUS "\xee\x89\xa8"  // U+E268
#define ICON_LUCIDE_PACKAGE_SEARCH "\xee\x89\xa9"  // U+E269
#define ICON_LUCIDE_PACKAGE_X "\xee\x89\xaa"  // U+E26A
#define ICON_LUCIDE_PAINT_BUCKET "\xee\x8b\xa6"  // U+E2E6
#define ICON_LUCIDE_PAINT_ROLLER "\xee\x96\x9e"  // U+E59E
#define ICON_LUCIDE_PAINTBRUSH "\xee\x8b\xa7"  // U+E2E7
#define ICON_LUCIDE_PAINTBRUSH_VERTICAL "\xee\x8b\xa8"  // U+E2E8
#define ICON_LUCIDE_PALETTE "\xee\x87\x9d"  // U+E1DD
#define ICON_LUCIDE_PANDA "\xee\x99\xa8"  // U+E668
#define ICON_LUCIDE_PANEL_BOTTOM "\xee\x90\xac"  // U+E42C
#define ICON_LUCIDE_PANEL_BOTTOM_CLOSE "\xee\x90\xad"  // U+E42D
#define ICON_LUCIDE_PANEL_BOTTOM_DASHED "\xee\x90\xae"  // U+E42E
#define ICON_LUCIDE_PANEL_BOTTOM_OPEN "\xee\x90\xaf"  // U+E42F
#define ICON_LUCIDE_PANEL_LEFT "\xee\x84\xaa"  // U+E12A
#define ICON_LUCIDE_PANEL_LEFT_CLOSE "\xee\x88\x9c"  // U+E21C
#define ICON_LUCIDE_PANEL_LEFT_DASHED "\xee\x90\xb0"  // U+E430
#define ICON_LUCIDE_PANEL_LEFT_OPEN "\xee\x88\x9d"  // U+E21D
#define ICON_LUCIDE_PANEL_LEFT_RIGHT_DASHED "\xee\x9a\x92"  // U+E692
#define ICON_LUCIDE_PANEL_RIGHT "\xee\x90\xb1"  // U+E431
#define ICON_LUCIDE_PANEL_RIGHT_CLOSE "\xee\x90\xb2"  // U+E432
#define ICON_LUCIDE_PANEL_RIGHT_DASHED "\xee\x90\xb3"  // U+E433
#define ICON_LUCIDE_PANEL_RIGHT_OPEN "\xee\x90\xb4"  // U+E434
#define ICON_LUCIDE_PANEL_TOP "\xee\x90\xb5"  // U+E435
#define ICON_LUCIDE_PANEL_TOP_BOTTOM_DASHED "\xee\x9a\x93"  // U+E693
#define ICON_LUCIDE_PANEL_TOP_CLOSE "\xee\x90\xb6"  // U+E436
#define ICON_LUCIDE_PANEL_TOP_DASHED "\xee\x90\xb7"  // U+E437
#define ICON_LUCIDE_PANEL_TOP_OPEN "\xee\x90\xb8"  // U+E438
#define ICON_LUCIDE_PANELS_LEFT_BOTTOM "\xee\x84\xab"  // U+E12B
#define ICON_LUCIDE_PANELS_RIGHT_BOTTOM "\xee\x96\x88"  // U+E588
#define ICON_LUCIDE_PANELS_TOP_LEFT "\xee\x84\xac"  // U+E12C
#define ICON_LUCIDE_PAPERCLIP "\xee\x84\xad"  // U+E12D
#define ICON_LUCIDE_PARENTHESES "\xee\x91\x84"  // U+E444
#define ICON_LUCIDE_PARKING_METER "\xee\x94\x80"  // U+E500
#define ICON_LUCIDE_PARTY_POPPER "\xee\x8d\x83"  // U+E343
#define ICON_LUCIDE_PAUSE "\xee\x84\xae"  // U+E12E
#define ICON_LUCIDE_PAW_PRINT "\xee\x93\xb5"  // U+E4F5
#define ICON_LUCIDE_PC_CASE "\xee\x91\x86"  // U+E446
#define ICON_LUCIDE_PEN "\xee\x84\xaf"  // U+E12F
#define ICON_LUCIDE_PEN_LINE "\xee\x84\xb0"  // U+E130
#define ICON_LUCIDE_PEN_OFF "\xee\x97\xae"  // U+E5EE
#define ICON_LUCIDE_PEN_TOOL "\xee\x84\xb1"  // U+E131
#define ICON_LUCIDE_PENCIL "\xee\x87\xb9"  // U+E1F9
#define ICON_LUCIDE_PENCIL_LINE "\xee\x93\xb0"  // U+E4F0
#define ICON_LUCIDE_PENCIL_OFF "\xee\x97\xaf"  // U+E5EF
#define ICON_LUCIDE_PENCIL_RULER "\xee\x93\xb1"  // U+E4F1
#define ICON_LUCIDE_PENTAGON "\xee\x94\xab"  // U+E52B
#define ICON_LUCIDE_PERCENT "\xee\x84\xb2"  // U+E132
#define ICON_LUCIDE_PERSON_STANDING "\xee\x88\x9e"  // U+E21E
#define ICON_LUCIDE_PHILIPPINE_PESO "\xee\x98\x84"  // U+E604
#define ICON_LUCIDE_PHONE "\xee\x84\xb3"  // U+E133
#define ICON_LUCIDE_PHONE_CALL "\xee\x84\xb4"  // U+E134
#define ICON_LUCIDE_PHONE_FORWARDED "\xee\x84\xb5"  // U+E135
#define ICON_LUCIDE_PHONE_INCOMING "\xee\x84\xb6"  // U+E136
#define ICON_LUCIDE_PHONE_MISSED "\xee\x84\xb7"  // U+E137
#define ICON_LUCIDE_PHONE_OFF "\xee\x84\xb8"  // U+E138
#define ICON_LUCIDE_PHONE_OUTGOING "\xee\x84\xb9"  // U+E139
#define ICON_LUCIDE_PI "\xee\x91\xb2"  // U+E472
#define ICON_LUCIDE_PIANO "\xee\x95\xa1"  // U+E561
#define ICON_LUCIDE_PICKAXE "\xee\x97\x86"  // U+E5C6
#define ICON_LUCIDE_PICTURE_IN_PICTURE "\xee\x8e\xae"  // U+E3AE
#define ICON_LUCIDE_PICTURE_IN_PICTURE_2 "\xee\x8e\xaf"  // U+E3AF
#define ICON_LUCIDE_PIGGY_BANK "\xee\x84\xba"  // U+E13A
#define ICON_LUCIDE_PILCROW "\xee\x8e\xa3"  // U+E3A3
#define ICON_LUCIDE_PILCROW_LEFT "\xee\x97\x9c"  // U+E5DC
#define ICON_LUCIDE_PILCROW_RIGHT "\xee\x97\x9d"  // U+E5DD
#define ICON_LUCIDE_PILL "\xee\x8e\xbd"  // U+E3BD
#define ICON_LUCIDE_PILL_BOTTLE "\xee\x97\xaa"  // U+E5EA
#define ICON_LUCIDE_PIN "\xee\x89\x99"  // U+E259
#define ICON_LUCIDE_PIN_OFF "\xee\x8a\xb6"  // U+E2B6
#define ICON_LUCIDE_PIPETTE "\xee\x84\xbb"  // U+E13B
#define ICON_LUCIDE_PIZZA "\xee\x8d\x94"  // U+E354
#define ICON_LUCIDE_PLANE "\xee\x87\x9e"  // U+E1DE
#define ICON_LUCIDE_PLANE_LANDING "\xee\x8f\x8d"  // U+E3CD
#define ICON_LUCIDE_PLANE_TAKEOFF "\xee\x8f\x8e"  // U+E3CE
#define ICON_LUCIDE_PLAY "\xee\x84\xbc"  // U+E13C
#define ICON_LUCIDE_PLUG "\xee\x8d\xbf"  // U+E37F
#define ICON_LUCIDE_PLUG_2 "\xee\x8e\x80"  // U+E380
#define ICON_LUCIDE_PLUG_ZAP "\xee\x91\x9c"  // U+E45C
#define ICON_LUCIDE_PLUS "\xee\x84\xbd"  // U+E13D
#define ICON_LUCIDE_POCKET "\xee\x84\xbe"  // U+E13E
#define ICON_LUCIDE_POCKET_KNIFE "\xee\x92\xa0"  // U+E4A0
#define ICON_LUCIDE_PODCAST "\xee\x87\xba"  // U+E1FA
#define ICON_LUCIDE_POINTER "\xee\x87\xa8"  // U+E1E8
#define ICON_LUCIDE_POINTER_OFF "\xee\x95\xbf"  // U+E57F
#define ICON_LUCIDE_POPCORN "\xee\x92\xbe"  // U+E4BE
#define ICON_LUCIDE_POPSICLE "\xee\x92\xbf"  // U+E4BF
#define ICON_LUCIDE_POUND_STERLING "\xee\x84\xbf"  // U+E13F
#define ICON_LUCIDE_POWER "\xee\x85\x80"  // U+E140
#define ICON_LUCIDE_POWER_OFF "\xee\x88\x89"  // U+E209
#define ICON_LUCIDE_PRESENTATION "\xee\x92\xae"  // U+E4AE
#define ICON_LUCIDE_PRINTER "\xee\x85\x81"  // U+E141
#define ICON_LUCIDE_PRINTER_CHECK "\xee\x97\xb5"  // U+E5F5
#define ICON_LUCIDE_PRINTER_X "\xee\x9a\xbb"  // U+E6BB
#define ICON_LUCIDE_PROJECTOR "\xee\x92\xaf"  // U+E4AF
#define ICON_LUCIDE_PROPORTIONS "\xee\x97\x8f"  // U+E5CF
#define ICON_LUCIDE_PUZZLE "\xee\x8a\x9c"  // U+E29C
#define ICON_LUCIDE_PYRAMID "\xee\x94\xac"  // U+E52C
#define ICON_LUCIDE_QR_CODE "\xee\x87\x9f"  // U+E1DF
#define ICON_LUCIDE_QUOTE "\xee\x88\xb9"  // U+E239
#define ICON_LUCIDE_RABBIT "\xee\x93\xb6"  // U+E4F6
#define ICON_LUCIDE_RADAR "\xee\x92\x97"  // U+E497
#define ICON_LUCIDE_RADIATION "\xee\x91\x82"  // U+E442
#define ICON_LUCIDE_RADICAL "\xee\x97\x82"  // U+E5C2
#define ICON_LUCIDE_RADIO "\xee\x85\x82"  // U+E142
#define ICON_LUCIDE_RADIO_RECEIVER "\xee\x87\xbb"  // U+E1FB
#define ICON_LUCIDE_RADIO_TOWER "\xee\x90\x84"  // U+E404
#define ICON_LUCIDE_RADIUS "\xee\x94\xad"  // U+E52D
#define ICON_LUCIDE_RAIL_SYMBOL "\xee\x94\x81"  // U+E501
#define ICON_LUCIDE_RAINBOW "\xee\x93\x82"  // U+E4C2
#define ICON_LUCIDE_RAT "\xee\x8f\xab"  // U+E3EB
#define ICON_LUCIDE_RATIO "\xee\x93\xa8"  // U+E4E8
#define ICON_LUCIDE_RECEIPT "\xee\x8f\x93"  // U+E3D3
#define ICON_LUCIDE_RECEIPT_CENT "\xee\x96\xa5"  // U+E5A5
#define ICON_LUCIDE_RECEIPT_EURO "\xee\x96\xa6"  // U+E5A6
#define ICON_LUCIDE_RECEIPT_INDIAN_RUPEE "\xee\x96\xa7"  // U+E5A7
#define ICON_LUCIDE_RECEIPT_JAPANESE_YEN "\xee\x96\xa8"  // U+E5A8
#define ICON_LUCIDE_RECEIPT_POUND_STERLING "\xee\x96\xa9"  // U+E5A9
#define ICON_LUCIDE_RECEIPT_RUSSIAN_RUBLE "\xee\x96\xaa"  // U+E5AA
#define ICON_LUCIDE_RECEIPT_SWISS_FRANC "\xee\x96\xab"  // U+E5AB
#define ICON_LUCIDE_RECEIPT_TEXT "\xee\x96\xac"  // U+E5AC
#define ICON_LUCIDE_RECEIPT_TURKISH_LIRA "\xee\x99\xbf"  // U+E67F
#define ICON_LUCIDE_RECTANGLE_CIRCLE "\xee\x99\xb3"  // U+E673
#define ICON_LUCIDE_RECTANGLE_ELLIPSIS "\xee\x88\x9f"  // U+E21F
#define ICON_LUCIDE_RECTANGLE_GOGGLES "\xee\x99\x96"  // U+E656
#define ICON_LUCIDE_RECTANGLE_HORIZONTAL "\xee\x8d\xb6"  // U+E376
#define ICON_LUCIDE_RECTANGLE_VERTICAL "\xee\x8d\xb7"  // U+E377
#define ICON_LUCIDE_RECYCLE "\xee\x8b\xa9"  // U+E2E9
#define ICON_LUCIDE_REDO "\xee\x85\x83"  // U+E143
#define ICON_LUCIDE_REDO_2 "\xee\x8a\xa0"  // U+E2A0
#define ICON_LUCIDE_REDO_DOT "\xee\x91\x90"  // U+E450
#define ICON_LUCIDE_REFRESH_CCW "\xee\x85\x84"  // U+E144
#define ICON_LUCIDE_REFRESH_CCW_DOT "\xee\x92\xb2"  // U+E4B2
#define ICON_LUCIDE_REFRESH_CW "\xee\x85\x85"  // U+E145
#define ICON_LUCIDE_REFRESH_CW_OFF "\xee\x92\x98"  // U+E498
#define ICON_LUCIDE_REFRIGERATOR "\xee\x8d\xbb"  // U+E37B
#define ICON_LUCIDE_REGEX "\xee\x87\xbc"  // U+E1FC
#define ICON_LUCIDE_REMOVE_FORMATTING "\xee\x8e\xb3"  // U+E3B3
#define ICON_LUCIDE_REPEAT "\xee\x85\x86"  // U+E146
#define ICON_LUCIDE_REPEAT_1 "\xee\x87\xbd"  // U+E1FD
#define ICON_LUCIDE_REPEAT_2 "\xee\x90\x91"  // U+E411
#define ICON_LUCIDE_REPLACE "\xee\x8f\x9b"  // U+E3DB
#define ICON_LUCIDE_REPLACE_ALL "\xee\x8f\x9c"  // U+E3DC
#define ICON_LUCIDE_REPLY "\xee\x88\xaa"  // U+E22A
#define ICON_LUCIDE_REPLY_ALL "\xee\x88\xab"  // U+E22B
#define ICON_LUCIDE_REWIND "\xee\x85\x87"  // U+E147
#define ICON_LUCIDE_RIBBON "\xee\x95\x98"  // U+E558
#define ICON_LUCIDE_ROCKET "\xee\x8a\x86"  // U+E286
#define ICON_LUCIDE_ROCKING_CHAIR "\xee\x88\xb3"  // U+E233
#define ICON_LUCIDE_ROLLER_COASTER "\xee\x92\x80"  // U+E480
#define ICON_LUCIDE_ROSE "\xee\x9a\x91"  // U+E691
#define ICON_LUCIDE_ROTATE_3D "\xee\x8b\xaa"  // U+E2EA
#define ICON_LUCIDE_ROTATE_CCW "\xee\x85\x88"  // U+E148
#define ICON_LUCIDE_ROTATE_CCW_KEY "\xee\x99\x90"  // U+E650
#define ICON_LUCIDE_ROTATE_CCW_SQUARE "\xee\x97\x90"  // U+E5D0
#define ICON_LUCIDE_ROTATE_CW "\xee\x85\x89"  // U+E149
#define ICON_LUCIDE_ROTATE_CW_SQUARE "\xee\x97\x91"  // U+E5D1
#define ICON_LUCIDE_ROUTE "\xee\x94\xbe"  // U+E53E
#define ICON_LUCIDE_ROUTE_OFF "\xee\x94\xbf"  // U+E53F
#define ICON_LUCIDE_ROUTER "\xee\x8e\xbf"  // U+E3BF
#define ICON_LUCIDE_ROWS_2 "\xee\x90\xb9"  // U+E439
#define ICON_LUCIDE_ROWS_3 "\xee\x96\x8a"  // U+E58A
#define ICON_LUCIDE_ROWS_4 "\xee\x96\x8b"  // U+E58B
#define ICON_LUCIDE_RSS "\xee\x85\x8a"  // U+E14A
#define ICON_LUCIDE_RULER "\xee\x85\x8b"  // U+E14B
#define ICON_LUCIDE_RULER_DIMENSION_LINE "\xee\x99\xa2"  // U+E662
#define ICON_LUCIDE_RUSSIAN_RUBLE "\xee\x85\x8c"  // U+E14C
#define ICON_LUCIDE_SAILBOAT "\xee\x8d\xbe"  // U+E37E
#define ICON_LUCIDE_SALAD "\xee\x8e\xa8"  // U+E3A8
#define ICON_LUCIDE_SANDWICH "\xee\x8e\xa9"  // U+E3A9
#define ICON_LUCIDE_SATELLITE "\xee\x91\x87"  // U+E447
#define ICON_LUCIDE_SATELLITE_DISH "\xee\x91\x88"  // U+E448
#define ICON_LUCIDE_SAUDI_RIYAL "\xee\x99\x8b"  // U+E64B
#define ICON_LUCIDE_SAVE "\xee\x85\x8d"  // U+E14D
#define ICON_LUCIDE_SAVE_ALL "\xee\x90\x8f"  // U+E40F
#define ICON_LUCIDE_SAVE_OFF "\xee\x97\xb3"  // U+E5F3
#define ICON_LUCIDE_SCALE "\xee\x88\x92"  // U+E212
#define ICON_LUCIDE_SCALE_3D "\xee\x8b\xab"  // U+E2EB
#define ICON_LUCIDE_SCALING "\xee\x8b\xac"  // U+E2EC
#define ICON_LUCIDE_SCAN "\xee\x89\x97"  // U+E257
#define ICON_LUCIDE_SCAN_BARCODE "\xee\x94\xb5"  // U+E535
#define ICON_LUCIDE_SCAN_EYE "\xee\x94\xb6"  // U+E536
#define ICON_LUCIDE_SCAN_FACE "\xee\x8d\xb1"  // U+E371
#define ICON_LUCIDE_SCAN_HEART "\xee\x98\xba"  // U+E63A
#define ICON_LUCIDE_SCAN_LINE "\xee\x89\x98"  // U+E258
#define ICON_LUCIDE_SCAN_QR_CODE "\xee\x97\xb6"  // U+E5F6
#define ICON_LUCIDE_SCAN_SEARCH "\xee\x94\xb7"  // U+E537
#define ICON_LUCIDE_SCAN_TEXT "\xee\x94\xb8"  // U+E538
#define ICON_LUCIDE_SCHOOL "\xee\x8f\xa3"  // U+E3E3
#define ICON_LUCIDE_SCISSORS "\xee\x85\x8e"  // U+E14E
#define ICON_LUCIDE_SCISSORS_LINE_DASHED "\xee\x93\xa9"  // U+E4E9
#define ICON_LUCIDE_SCOOTER "\xee\x9a\xac"  // U+E6AC
#define ICON_LUCIDE_SCREEN_SHARE "\xee\x85\x8f"  // U+E14F
#define ICON_LUCIDE_SCREEN_SHARE_OFF "\xee\x85\x90"  // U+E150
#define ICON_LUCIDE_SCROLL "\xee\x8b\xad"  // U+E2ED
#define ICON_LUCIDE_SCROLL_TEXT "\xee\x91\x9f"  // U+E45F
#define ICON_LUCIDE_SEARCH "\xee\x85\x91"  // U+E151
#define ICON_LUCIDE_SEARCH_ALERT "\xee\x9a\xb4"  // U+E6B4
#define ICON_LUCIDE_SEARCH_CHECK "\xee\x92\xaa"  // U+E4AA
#define ICON_LUCIDE_SEARCH_CODE "\xee\x92\xab"  // U+E4AB
#define ICON_LUCIDE_SEARCH_SLASH "\xee\x92\xac"  // U+E4AC
#define ICON_LUCIDE_SEARCH_X "\xee\x92\xad"  // U+E4AD
#define ICON_LUCIDE_SECTION "\xee\x97\xa8"  // U+E5E8
#define ICON_LUCIDE_SEND "\xee\x85\x92"  // U+E152
#define ICON_LUCIDE_SEND_HORIZONTAL "\xee\x93\xb2"  // U+E4F2
#define ICON_LUCIDE_SEND_TO_BACK "\xee\x93\xb3"  // U+E4F3
#define ICON_LUCIDE_SEPARATOR_HORIZONTAL "\xee\x87\x88"  // U+E1C8
#define ICON_LUCIDE_SEPARATOR_VERTICAL "\xee\x87\x89"  // U+E1C9
#define ICON_LUCIDE_SERVER "\xee\x85\x93"  // U+E153
#define ICON_LUCIDE_SERVER_COG "\xee\x8d\x81"  // U+E341
#define ICON_LUCIDE_SERVER_CRASH "\xee\x87\xa9"  // U+E1E9
#define ICON_LUCIDE_SERVER_OFF "\xee\x87\xaa"  // U+E1EA
#define ICON_LUCIDE_SETTINGS "\xee\x85\x94"  // U+E154
#define ICON_LUCIDE_SETTINGS_2 "\xee\x89\x85"  // U+E245
#define ICON_LUCIDE_SHAPES "\xee\x92\xb3"  // U+E4B3
#define ICON_LUCIDE_SHARE "\xee\x85\x95"  // U+E155
#define ICON_LUCIDE_SHARE_2 "\xee\x85\x96"  // U+E156
#define ICON_LUCIDE_SHEET "\xee\x85\x97"  // U+E157
#define ICON_LUCIDE_SHELL "\xee\x93\xb7"  // U+E4F7
#define ICON_LUCIDE_SHELVING_UNIT "\xee\x9b\x87"  // U+E6C7
#define ICON_LUCIDE_SHIELD "\xee\x85\x98"  // U+E158
#define ICON_LUCIDE_SHIELD_ALERT "\xee\x87\xbe"  // U+E1FE
#define ICON_LUCIDE_SHIELD_BAN "\xee\x85\x99"  // U+E159
#define ICON_LUCIDE_SHIELD_CHECK "\xee\x87\xbf"  // U+E1FF
#define ICON_LUCIDE_SHIELD_ELLIPSIS "\xee\x94\x96"  // U+E516
#define ICON_LUCIDE_SHIELD_HALF "\xee\x94\x97"  // U+E517
#define ICON_LUCIDE_SHIELD_MINUS "\xee\x94\x98"  // U+E518
#define ICON_LUCIDE_SHIELD_OFF "\xee\x85\x9a"  // U+E15A
#define ICON_LUCIDE_SHIELD_PLUS "\xee\x94\x99"  // U+E519
#define ICON_LUCIDE_SHIELD_QUESTION_MARK "\xee\x90\x8e"  // U+E40E
#define ICON_LUCIDE_SHIELD_USER "\xee\x99\x87"  // U+E647
#define ICON_LUCIDE_SHIELD_X "\xee\x88\x80"  // U+E200
#define ICON_LUCIDE_SHIP "\xee\x8e\xba"  // U+E3BA
#define ICON_LUCIDE_SHIP_WHEEL "\xee\x94\x82"  // U+E502
#define ICON_LUCIDE_SHIRT "\xee\x87\x8a"  // U+E1CA
#define ICON_LUCIDE_SHOPPING_BAG "\xee\x85\x9b"  // U+E15B
#define ICON_LUCIDE_SHOPPING_BASKET "\xee\x93\xaa"  // U+E4EA
#define ICON_LUCIDE_SHOPPING_CART "\xee\x85\x9c"  // U+E15C
#define ICON_LUCIDE_SHOVEL "\xee\x85\x9d"  // U+E15D
#define ICON_LUCIDE_SHOWER_HEAD "\xee\x8d\xbc"  // U+E37C
#define ICON_LUCIDE_SHREDDER "\xee\x99\x9b"  // U+E65B
#define ICON_LUCIDE_SHRIMP "\xee\x99\x89"  // U+E649
#define ICON_LUCIDE_SHRINK "\xee\x88\xa0"  // U+E220
#define ICON_LUCIDE_SHRUB "\xee\x8b\xae"  // U+E2EE
#define ICON_LUCIDE_SHUFFLE "\xee\x85\x9e"  // U+E15E
#define ICON_LUCIDE_SIGMA "\xee\x88\x81"  // U+E201
#define ICON_LUCIDE_SIGNAL "\xee\x89\x9f"  // U+E25F
#define ICON_LUCIDE_SIGNAL_HIGH "\xee\x89\xa0"  // U+E260
#define ICON_LUCIDE_SIGNAL_LOW "\xee\x89\xa1"  // U+E261
#define ICON_LUCIDE_SIGNAL_MEDIUM "\xee\x89\xa2"  // U+E262
#define ICON_LUCIDE_SIGNAL_ZERO "\xee\x89\xa3"  // U+E263
#define ICON_LUCIDE_SIGNATURE "\xee\x97\xb2"  // U+E5F2
#define ICON_LUCIDE_SIGNPOST "\xee\x95\x80"  // U+E540
#define ICON_LUCIDE_SIGNPOST_BIG "\xee\x95\x81"  // U+E541
#define ICON_LUCIDE_SIREN "\xee\x8b\xaf"  // U+E2EF
#define ICON_LUCIDE_SKIP_BACK "\xee\x85\x9f"  // U+E15F
#define ICON_LUCIDE_SKIP_FORWARD "\xee\x85\xa0"  // U+E160
#define ICON_LUCIDE_SKULL "\xee\x88\xa1"  // U+E221
#define ICON_LUCIDE_SLACK "\xee\x85\xa1"  // U+E161
#define ICON_LUCIDE_SLASH "\xee\x94\x9d"  // U+E51D
#define ICON_LUCIDE_SLICE "\xee\x8b\xb0"  // U+E2F0
#define ICON_LUCIDE_SLIDERS_HORIZONTAL "\xee\x8a\x9a"  // U+E29A
#define ICON_LUCIDE_SLIDERS_VERTICAL "\xee\x85\xa2"  // U+E162
#define ICON_LUCIDE_SMARTPHONE "\xee\x85\xa3"  // U+E163
#define ICON_LUCIDE_SMARTPHONE_CHARGING "\xee\x88\xae"  // U+E22E
#define ICON_LUCIDE_SMARTPHONE_NFC "\xee\x8f\x84"  // U+E3C4
#define ICON_LUCIDE_SMILE "\xee\x85\xa4"  // U+E164
#define ICON_LUCIDE_SMILE_PLUS "\xee\x8c\x81"  // U+E301
#define ICON_LUCIDE_SNAIL "\xee\x93\xb8"  // U+E4F8
#define ICON_LUCIDE_SNOWFLAKE "\xee\x85\xa5"  // U+E165
#define ICON_LUCIDE_SOAP_DISPENSER_DROPLET "\xee\x99\xa9"  // U+E669
#define ICON_LUCIDE_SOFA "\xee\x8b\x84"  // U+E2C4
#define ICON_LUCIDE_SOLAR_PANEL "\xee\x9a\x9f"  // U+E69F
#define ICON_LUCIDE_SOUP "\xee\x8e\xaa"  // U+E3AA
#define ICON_LUCIDE_SPACE "\xee\x8f\x9d"  // U+E3DD
#define ICON_LUCIDE_SPADE "\xee\x92\x99"  // U+E499
#define ICON_LUCIDE_SPARKLE "\xee\x91\xbe"  // U+E47E
#define ICON_LUCIDE_SPARKLES "\xee\x90\x92"  // U+E412
#define ICON_LUCIDE_SPEAKER "\xee\x85\xa6"  // U+E166
#define ICON_LUCIDE_SPEECH "\xee\x94\x9e"  // U+E51E
#define ICON_LUCIDE_SPELL_CHECK "\xee\x92\x9a"  // U+E49A
#define ICON_LUCIDE_SPELL_CHECK_2 "\xee\x92\x9b"  // U+E49B
#define ICON_LUCIDE_SPLINE "\xee\x8e\x8b"  // U+E38B
#define ICON_LUCIDE_SPLINE_POINTER "\xee\x99\x8f"  // U+E64F
#define ICON_LUCIDE_SPLIT "\xee\x91\x80"  // U+E440
#define ICON_LUCIDE_SPOOL "\xee\x99\xb7"  // U+E677
#define ICON_LUCIDE_SPOTLIGHT "\xee\x9a\x82"  // U+E682
#define ICON_LUCIDE_SPRAY_CAN "\xee\x92\x95"  // U+E495
#define ICON_LUCIDE_SPROUT "\xee\x87\xab"  // U+E1EB
#define ICON_LUCIDE_SQUARE "\xee\x85\xa7"  // U+E167
#define ICON_LUCIDE_SQUARE_ACTIVITY "\xee\x92\xb4"  // U+E4B4
#define ICON_LUCIDE_SQUARE_ARROW_DOWN "\xee\x90\xa7"  // U+E427
#define ICON_LUCIDE_SQUARE_ARROW_DOWN_LEFT "\xee\x92\xb5"  // U+E4B5
#define ICON_LUCIDE_SQUARE_ARROW_DOWN_RIGHT "\xee\x92\xb6"  // U+E4B6
#define ICON_LUCIDE_SQUARE_ARROW_LEFT "\xee\x90\xa8"  // U+E428
#define ICON_LUCIDE_SQUARE_ARROW_OUT_DOWN_LEFT "\xee\x96\xa1"  // U+E5A1
#define ICON_LUCIDE_SQUARE_ARROW_OUT_DOWN_RIGHT "\xee\x96\xa2"  // U+E5A2
#define ICON_LUCIDE_SQUARE_ARROW_OUT_UP_LEFT "\xee\x96\xa3"  // U+E5A3
#define ICON_LUCIDE_SQUARE_ARROW_OUT_UP_RIGHT "\xee\x96\xa4"  // U+E5A4
#define ICON_LUCIDE_SQUARE_ARROW_RIGHT "\xee\x90\xa9"  // U+E429
#define ICON_LUCIDE_SQUARE_ARROW_RIGHT_ENTER "\xee\x9b\x8e"  // U+E6CE
#define ICON_LUCIDE_SQUARE_ARROW_RIGHT_EXIT "\xee\x9b\x8f"  // U+E6CF
#define ICON_LUCIDE_SQUARE_ARROW_UP "\xee\x90\xaa"  // U+E42A
#define ICON_LUCIDE_SQUARE_ARROW_UP_LEFT "\xee\x92\xb7"  // U+E4B7
#define ICON_LUCIDE_SQUARE_ARROW_UP_RIGHT "\xee\x92\xb8"  // U+E4B8
#define ICON_LUCIDE_SQUARE_ASTERISK "\xee\x85\xa8"  // U+E168
#define ICON_LUCIDE_SQUARE_BOTTOM_DASHED_SCISSORS "\xee\x93\xab"  // U+E4EB
#define ICON_LUCIDE_SQUARE_CENTERLINE_DASHED_HORIZONTAL "\xee\x8d\x9f"  // U+E35F
#define ICON_LUCIDE_SQUARE_CENTERLINE_DASHED_VERTICAL "\xee\x8d\xa0"  // U+E360
#define ICON_LUCIDE_SQUARE_CHART_GANTT "\xee\x85\xa9"  // U+E169
#define ICON_LUCIDE_SQUARE_CHECK "\xee\x95\x99"  // U+E559
#define ICON_LUCIDE_SQUARE_CHECK_BIG "\xee\x85\xaa"  // U+E16A
#define ICON_LUCIDE_SQUARE_CHEVRON_DOWN "\xee\x8f\x8f"  // U+E3CF
#define ICON_LUCIDE_SQUARE_CHEVRON_LEFT "\xee\x8f\x90"  // U+E3D0
#define ICON_LUCIDE_SQUARE_CHEVRON_RIGHT "\xee\x8f\x91"  // U+E3D1
#define ICON_LUCIDE_SQUARE_CHEVRON_UP "\xee\x8f\x92"  // U+E3D2
#define ICON_LUCIDE_SQUARE_CODE "\xee\x85\xab"  // U+E16B
#define ICON_LUCIDE_SQUARE_DASHED "\xee\x87\x8b"  // U+E1CB
#define ICON_LUCIDE_SQUARE_DASHED_BOTTOM "\xee\x93\x80"  // U+E4C0
#define ICON_LUCIDE_SQUARE_DASHED_BOTTOM_CODE "\xee\x93\x81"  // U+E4C1
#define ICON_LUCIDE_SQUARE_DASHED_KANBAN "\xee\x85\xac"  // U+E16C
#define ICON_LUCIDE_SQUARE_DASHED_MOUSE_POINTER "\xee\x94\x89"  // U+E509
#define ICON_LUCIDE_SQUARE_DASHED_TOP_SOLID "\xee\x99\xac"  // U+E66C
#define ICON_LUCIDE_SQUARE_DIVIDE "\xee\x85\xad"  // U+E16D
#define ICON_LUCIDE_SQUARE_DOT "\xee\x85\xae"  // U+E16E
#define ICON_LUCIDE_SQUARE_EQUAL "\xee\x85\xaf"  // U+E16F
#define ICON_LUCIDE_SQUARE_FUNCTION "\xee\x88\xad"  // U+E22D
#define ICON_LUCIDE_SQUARE_KANBAN "\xee\x85\xb0"  // U+E170
#define ICON_LUCIDE_SQUARE_LIBRARY "\xee\x95\x8f"  // U+E54F
#define ICON_LUCIDE_SQUARE_M "\xee\x94\x83"  // U+E503
#define ICON_LUCIDE_SQUARE_MENU "\xee\x91\x93"  // U+E453
#define ICON_LUCIDE_SQUARE_MINUS "\xee\x85\xb1"  // U+E171
#define ICON_LUCIDE_SQUARE_MOUSE_POINTER "\xee\x88\x82"  // U+E202
#define ICON_LUCIDE_SQUARE_PARKING "\xee\x8f\x8b"  // U+E3CB
#define ICON_LUCIDE_SQUARE_PARKING_OFF "\xee\x8f\x8c"  // U+E3CC
#define ICON_LUCIDE_SQUARE_PAUSE "\xee\x9a\x84"  // U+E684
#define ICON_LUCIDE_SQUARE_PEN "\xee\x85\xb2"  // U+E172
#define ICON_LUCIDE_SQUARE_PERCENT "\xee\x94\x9c"  // U+E51C
#define ICON_LUCIDE_SQUARE_PI "\xee\x92\x88"  // U+E488
#define ICON_LUCIDE_SQUARE_PILCROW "\xee\x92\x8b"  // U+E48B
#define ICON_LUCIDE_SQUARE_PLAY "\xee\x92\x81"  // U+E481
#define ICON_LUCIDE_SQUARE_PLUS "\xee\x85\xb3"  // U+E173
#define ICON_LUCIDE_SQUARE_POWER "\xee\x95\x91"  // U+E551
#define ICON_LUCIDE_SQUARE_RADICAL "\xee\x97\x83"  // U+E5C3
#define ICON_LUCIDE_SQUARE_ROUND_CORNER "\xee\x99\x88"  // U+E648
#define ICON_LUCIDE_SQUARE_SCISSORS "\xee\x93\xac"  // U+E4EC
#define ICON_LUCIDE_SQUARE_SIGMA "\xee\x92\x89"  // U+E489
#define ICON_LUCIDE_SQUARE_SLASH "\xee\x85\xb4"  // U+E174
#define ICON_LUCIDE_SQUARE_SPLIT_HORIZONTAL "\xee\x8e\xb6"  // U+E3B6
#define ICON_LUCIDE_SQUARE_SPLIT_VERTICAL "\xee\x8e\xb7"  // U+E3B7
#define ICON_LUCIDE_SQUARE_SQUARE "\xee\x98\x8e"  // U+E60E
#define ICON_LUCIDE_SQUARE_STACK "\xee\x92\xa2"  // U+E4A2
#define ICON_LUCIDE_SQUARE_STAR "\xee\x9a\x8e"  // U+E68E
#define ICON_LUCIDE_SQUARE_STOP "\xee\x9a\x85"  // U+E685
#define ICON_LUCIDE_SQUARE_TERMINAL "\xee\x88\x8a"  // U+E20A
#define ICON_LUCIDE_SQUARE_USER "\xee\x91\xa5"  // U+E465
#define ICON_LUCIDE_SQUARE_USER_ROUND "\xee\x91\xa6"  // U+E466
#define ICON_LUCIDE_SQUARE_X "\xee\x85\xb5"  // U+E175
#define ICON_LUCIDE_SQUARES_EXCLUDE "\xee\x99\x97"  // U+E657
#define ICON_LUCIDE_SQUARES_INTERSECT "\xee\x99\x98"  // U+E658
#define ICON_LUCIDE_SQUARES_SUBTRACT "\xee\x99\x99"  // U+E659
#define ICON_LUCIDE_SQUARES_UNITE "\xee\x99\x9a"  // U+E65A
#define ICON_LUCIDE_SQUIRCLE "\xee\x95\xba"  // U+E57A
#define ICON_LUCIDE_SQUIRCLE_DASHED "\xee\x99\xb9"  // U+E679
#define ICON_LUCIDE_SQUIRREL "\xee\x92\x9f"  // U+E49F
#define ICON_LUCIDE_STAMP "\xee\x8e\xbb"  // U+E3BB
#define ICON_LUCIDE_STAR "\xee\x85\xb6"  // U+E176
#define ICON_LUCIDE_STAR_HALF "\xee\x88\x8b"  // U+E20B
#define ICON_LUCIDE_STAR_OFF "\xee\x8a\xb0"  // U+E2B0
#define ICON_LUCIDE_STEP_BACK "\xee\x8f\xa9"  // U+E3E9
#define ICON_LUCIDE_STEP_FORWARD "\xee\x8f\xaa"  // U+E3EA
#define ICON_LUCIDE_STETHOSCOPE "\xee\x8b\xb1"  // U+E2F1
#define ICON_LUCIDE_STICKER "\xee\x8c\x82"  // U+E302
#define ICON_LUCIDE_STICKY_NOTE "\xee\x8c\x83"  // U+E303
#define ICON_LUCIDE_STONE "\xee\x9a\xb8"  // U+E6B8
#define ICON_LUCIDE_STORE "\xee\x8f\xa4"  // U+E3E4
#define ICON_LUCIDE_STRETCH_HORIZONTAL "\xee\x89\xbc"  // U+E27C
#define ICON_LUCIDE_STRETCH_VERTICAL "\xee\x89\xbd"  // U+E27D
#define ICON_LUCIDE_STRIKETHROUGH "\xee\x85\xb7"  // U+E177
#define ICON_LUCIDE_SUBSCRIPT "\xee\x89\x9c"  // U+E25C
#define ICON_LUCIDE_SUN "\xee\x85\xb8"  // U+E178
#define ICON_LUCIDE_SUN_DIM "\xee\x8a\x99"  // U+E299
#define ICON_LUCIDE_SUN_MEDIUM "\xee\x8a\xb1"  // U+E2B1
#define ICON_LUCIDE_SUN_MOON "\xee\x8a\xb2"  // U+E2B2
#define ICON_LUCIDE_SUN_SNOW "\xee\x8d\xb2"  // U+E372
#define ICON_LUCIDE_SUNRISE "\xee\x85\xb9"  // U+E179
#define ICON_LUCIDE_SUNSET "\xee\x85\xba"  // U+E17A
#define ICON_LUCIDE_SUPERSCRIPT "\xee\x89\x9e"  // U+E25E
#define ICON_LUCIDE_SWATCH_BOOK "\xee\x96\x9f"  // U+E59F
#define ICON_LUCIDE_SWISS_FRANC "\xee\x85\xbb"  // U+E17B
#define ICON_LUCIDE_SWITCH_CAMERA "\xee\x85\xbc"  // U+E17C
#define ICON_LUCIDE_SWORD "\xee\x8a\xb3"  // U+E2B3
#define ICON_LUCIDE_SWORDS "\xee\x8a\xb4"  // U+E2B4
#define ICON_LUCIDE_SYRINGE "\xee\x8b\xb2"  // U+E2F2
#define ICON_LUCIDE_TABLE "\xee\x85\xbd"  // U+E17D
#define ICON_LUCIDE_TABLE_2 "\xee\x8b\xb9"  // U+E2F9
#define ICON_LUCIDE_TABLE_CELLS_MERGE "\xee\x97\x87"  // U+E5C7
#define ICON_LUCIDE_TABLE_CELLS_SPLIT "\xee\x97\x88"  // U+E5C8
#define ICON_LUCIDE_TABLE_COLUMNS_SPLIT "\xee\x97\x89"  // U+E5C9
#define ICON_LUCIDE_TABLE_OF_CONTENTS "\xee\x98\x9e"  // U+E61E
#define ICON_LUCIDE_TABLE_PROPERTIES "\xee\x93\x9b"  // U+E4DB
#define ICON_LUCIDE_TABLE_ROWS_SPLIT "\xee\x97\x8a"  // U+E5CA
#define ICON_LUCIDE_TABLET "\xee\x85\xbe"  // U+E17E
#define ICON_LUCIDE_TABLET_SMARTPHONE "\xee\x94\x8a"  // U+E50A
#define ICON_LUCIDE_TABLETS "\xee\x8e\xbe"  // U+E3BE
#define ICON_LUCIDE_TAG "\xee\x85\xbf"  // U+E17F
#define ICON_LUCIDE_TAGS "\xee\x8d\x9c"  // U+E35C
#define ICON_LUCIDE_TALLY_1 "\xee\x93\x96"  // U+E4D6
#define ICON_LUCIDE_TALLY_2 "\xee\x93\x97"  // U+E4D7
#define ICON_LUCIDE_TALLY_3 "\xee\x93\x98"  // U+E4D8
#define ICON_LUCIDE_TALLY_4 "\xee\x93\x99"  // U+E4D9
#define ICON_LUCIDE_TALLY_5 "\xee\x93\x9a"  // U+E4DA
#define ICON_LUCIDE_TANGENT "\xee\x94\xae"  // U+E52E
#define ICON_LUCIDE_TARGET "\xee\x86\x80"  // U+E180
#define ICON_LUCIDE_TELESCOPE "\xee\x97\x85"  // U+E5C5
#define ICON_LUCIDE_TENT "\xee\x88\xa7"  // U+E227
#define ICON_LUCIDE_TENT_TREE "\xee\x94\xbb"  // U+E53B
#define ICON_LUCIDE_TERMINAL "\xee\x86\x81"  // U+E181
#define ICON_LUCIDE_TEST_TUBE "\xee\x90\x85"  // U+E405
#define ICON_LUCIDE_TEST_TUBE_DIAGONAL "\xee\x90\x86"  // U+E406
#define ICON_LUCIDE_TEST_TUBES "\xee\x90\x87"  // U+E407
#define ICON_LUCIDE_TEXT_ALIGN_CENTER "\xee\x86\x82"  // U+E182
#define ICON_LUCIDE_TEXT_ALIGN_END "\xee\x86\x83"  // U+E183
#define ICON_LUCIDE_TEXT_ALIGN_JUSTIFY "\xee\x86\x84"  // U+E184
#define ICON_LUCIDE_TEXT_ALIGN_START "\xee\x86\x85"  // U+E185
#define ICON_LUCIDE_TEXT_CURSOR "\xee\x89\xa4"  // U+E264
#define ICON_LUCIDE_TEXT_CURSOR_INPUT "\xee\x89\xa5"  // U+E265
#define ICON_LUCIDE_TEXT_INITIAL "\xee\x98\x85"  // U+E605
#define ICON_LUCIDE_TEXT_QUOTE "\xee\x92\x9e"  // U+E49E
#define ICON_LUCIDE_TEXT_SEARCH "\xee\x96\xad"  // U+E5AD
#define ICON_LUCIDE_TEXT_SELECT "\xee\x8f\x9e"  // U+E3DE
#define ICON_LUCIDE_TEXT_WRAP "\xee\x89\x88"  // U+E248
#define ICON_LUCIDE_THEATER "\xee\x94\xa2"  // U+E522
#define ICON_LUCIDE_THERMOMETER "\xee\x86\x86"  // U+E186
#define ICON_LUCIDE_THERMOMETER_SNOWFLAKE "\xee\x86\x87"  // U+E187
#define ICON_LUCIDE_THERMOMETER_SUN "\xee\x86\x88"  // U+E188
#define ICON_LUCIDE_THUMBS_DOWN "\xee\x86\x89"  // U+E189
#define ICON_LUCIDE_THUMBS_UP "\xee\x86\x8a"  // U+E18A
#define ICON_LUCIDE_TICKET "\xee\x88\x8f"  // U+E20F
#define ICON_LUCIDE_TICKET_CHECK "\xee\x96\xae"  // U+E5AE
#define ICON_LUCIDE_TICKET_MINUS "\xee\x96\xaf"  // U+E5AF
#define ICON_LUCIDE_TICKET_PERCENT "\xee\x96\xb0"  // U+E5B0
#define ICON_LUCIDE_TICKET_PLUS "\xee\x96\xb1"  // U+E5B1
#define ICON_LUCIDE_TICKET_SLASH "\xee\x96\xb2"  // U+E5B2
#define ICON_LUCIDE_TICKET_X "\xee\x96\xb3"  // U+E5B3
#define ICON_LUCIDE_TICKETS "\xee\x98\xa2"  // U+E622
#define ICON_LUCIDE_TICKETS_PLANE "\xee\x98\xa3"  // U+E623
#define ICON_LUCIDE_TIMER "\xee\x87\xa0"  // U+E1E0
#define ICON_LUCIDE_TIMER_OFF "\xee\x89\x89"  // U+E249
#define ICON_LUCIDE_TIMER_RESET "\xee\x88\xb6"  // U+E236
#define ICON_LUCIDE_TOGGLE_LEFT "\xee\x86\x8b"  // U+E18B
#define ICON_LUCIDE_TOGGLE_RIGHT "\xee\x86\x8c"  // U+E18C
#define ICON_LUCIDE_TOILET "\xee\x98\xb5"  // U+E635
#define ICON_LUCIDE_TOOL_CASE "\xee\x99\xbd"  // U+E67D
#define ICON_LUCIDE_TOOLBOX "\xee\x9a\xb9"  // U+E6B9
#define ICON_LUCIDE_TORNADO "\xee\x88\x98"  // U+E218
#define ICON_LUCIDE_TORUS "\xee\x94\xaf"  // U+E52F
#define ICON_LUCIDE_TOUCHPAD "\xee\x91\x89"  // U+E449
#define ICON_LUCIDE_TOUCHPAD_OFF "\xee\x91\x8a"  // U+E44A
#define ICON_LUCIDE_TOWEL_RACK "\xee\x9b\x86"  // U+E6C6
#define ICON_LUCIDE_TOWER_CONTROL "\xee\x8e\xbc"  // U+E3BC
#define ICON_LUCIDE_TOY_BRICK "\xee\x8d\x87"  // U+E347
#define ICON_LUCIDE_TRACTOR "\xee\x94\x84"  // U+E504
#define ICON_LUCIDE_TRAFFIC_CONE "\xee\x94\x85"  // U+E505
#define ICON_LUCIDE_TRAIN_FRONT "\xee\x94\x86"  // U+E506
#define ICON_LUCIDE_TRAIN_FRONT_TUNNEL "\xee\x94\x87"  // U+E507
#define ICON_LUCIDE_TRAIN_TRACK "\xee\x94\x88"  // U+E508
#define ICON_LUCIDE_TRAM_FRONT "\xee\x8a\xa9"  // U+E2A9
#define ICON_LUCIDE_TRANSGENDER "\xee\x99\x84"  // U+E644
#define ICON_LUCIDE_TRASH "\xee\x86\x8d"  // U+E18D
#define ICON_LUCIDE_TRASH_2 "\xee\x86\x8e"  // U+E18E
#define ICON_LUCIDE_TREE_DECIDUOUS "\xee\x8b\xb3"  // U+E2F3
#define ICON_LUCIDE_TREE_PALM "\xee\x8a\x81"  // U+E281
#define ICON_LUCIDE_TREE_PINE "\xee\x8b\xb4"  // U+E2F4
#define ICON_LUCIDE_TREES "\xee\x8b\xb5"  // U+E2F5
#define ICON_LUCIDE_TRELLO "\xee\x86\x8f"  // U+E18F
#define ICON_LUCIDE_TRENDING_DOWN "\xee\x86\x90"  // U+E190
#define ICON_LUCIDE_TRENDING_UP "\xee\x86\x91"  // U+E191
#define ICON_LUCIDE_TRENDING_UP_DOWN "\xee\x98\xa5"  // U+E625
#define ICON_LUCIDE_TRIANGLE "\xee\x86\x92"  // U+E192
#define ICON_LUCIDE_TRIANGLE_ALERT "\xee\x86\x93"  // U+E193
#define ICON_LUCIDE_TRIANGLE_DASHED "\xee\x98\xbd"  // U+E63D
#define ICON_LUCIDE_TRIANGLE_RIGHT "\xee\x93\xad"  // U+E4ED
#define ICON_LUCIDE_TROPHY "\xee\x8d\xb3"  // U+E373
#define ICON_LUCIDE_TRUCK "\xee\x86\x94"  // U+E194
#define ICON_LUCIDE_TRUCK_ELECTRIC "\xee\x99\x9f"  // U+E65F
#define ICON_LUCIDE_TURKISH_LIRA "\xee\x9a\x80"  // U+E680
#define ICON_LUCIDE_TURNTABLE "\xee\x9a\x8c"  // U+E68C
#define ICON_LUCIDE_TURTLE "\xee\x93\xb9"  // U+E4F9
#define ICON_LUCIDE_TV "\xee\x86\x95"  // U+E195
#define ICON_LUCIDE_TV_MINIMAL "\xee\x88\x83"  // U+E203
#define ICON_LUCIDE_TV_MINIMAL_PLAY "\xee\x97\xac"  // U+E5EC
#define ICON_LUCIDE_TWITCH "\xee\x86\x96"  // U+E196
#define ICON_LUCIDE_TWITTER "\xee\x86\x97"  // U+E197
#define ICON_LUCIDE_TYPE "\xee\x86\x98"  // U+E198
#define ICON_LUCIDE_TYPE_OUTLINE "\xee\x98\x82"  // U+E602
#define ICON_LUCIDE_UMBRELLA "\xee\x86\x99"  // U+E199
#define ICON_LUCIDE_UMBRELLA_OFF "\xee\x95\x83"  // U+E543
#define ICON_LUCIDE_UNDERLINE "\xee\x86\x9a"  // U+E19A
#define ICON_LUCIDE_UNDO "\xee\x86\x9b"  // U+E19B
#define ICON_LUCIDE_UNDO_2 "\xee\x8a\xa1"  // U+E2A1
#define ICON_LUCIDE_UNDO_DOT "\xee\x91\x91"  // U+E451
#define ICON_LUCIDE_UNFOLD_HORIZONTAL "\xee\x90\xbd"  // U+E43D
#define ICON_LUCIDE_UNFOLD_VERTICAL "\xee\x90\xbe"  // U+E43E
#define ICON_LUCIDE_UNGROUP "\xee\x91\xa7"  // U+E467
#define ICON_LUCIDE_UNIVERSITY "\xee\x8f\xa5"  // U+E3E5
#define ICON_LUCIDE_UNLINK "\xee\x86\x9c"  // U+E19C
#define ICON_LUCIDE_UNLINK_2 "\xee\x86\x9d"  // U+E19D
#define ICON_LUCIDE_UNPLUG "\xee\x91\x9d"  // U+E45D
#define ICON_LUCIDE_UPLOAD "\xee\x86\x9e"  // U+E19E
#define ICON_LUCIDE_USB "\xee\x8d\x96"  // U+E356
#define ICON_LUCIDE_USER "\xee\x86\x9f"  // U+E19F
#define ICON_LUCIDE_USER_CHECK "\xee\x86\xa0"  // U+E1A0
#define ICON_LUCIDE_USER_COG "\xee\x8d\x82"  // U+E342
#define ICON_LUCIDE_USER_KEY "\xee\x9a\xbd"  // U+E6BD
#define ICON_LUCIDE_USER_LOCK "\xee\x99\xa0"  // U+E660
#define ICON_LUCIDE_USER_MINUS "\xee\x86\xa1"  // U+E1A1
#define ICON_LUCIDE_USER_PEN "\xee\x97\xbc"  // U+E5FC
#define ICON_LUCIDE_USER_PLUS "\xee\x86\xa2"  // U+E1A2
#define ICON_LUCIDE_USER_ROUND "\xee\x91\xa8"  // U+E468
#define ICON_LUCIDE_USER_ROUND_CHECK "\xee\x91\xa9"  // U+E469
#define ICON_LUCIDE_USER_ROUND_COG "\xee\x91\xaa"  // U+E46A
#define ICON_LUCIDE_USER_ROUND_KEY "\xee\x9a\xbe"  // U+E6BE
#define ICON_LUCIDE_USER_ROUND_MINUS "\xee\x91\xab"  // U+E46B
#define ICON_LUCIDE_USER_ROUND_PEN "\xee\x97\xbd"  // U+E5FD
#define ICON_LUCIDE_USER_ROUND_PLUS "\xee\x91\xac"  // U+E46C
#define ICON_LUCIDE_USER_ROUND_SEARCH "\xee\x95\xb8"  // U+E578
#define ICON_LUCIDE_USER_ROUND_X "\xee\x91\xad"  // U+E46D
#define ICON_LUCIDE_USER_SEARCH "\xee\x95\xb9"  // U+E579
#define ICON_LUCIDE_USER_STAR "\xee\x9a\x87"  // U+E687
#define ICON_LUCIDE_USER_X "\xee\x86\xa3"  // U+E1A3
#define ICON_LUCIDE_USERS "\xee\x86\xa4"  // U+E1A4
#define ICON_LUCIDE_USERS_ROUND "\xee\x91\xae"  // U+E46E
#define ICON_LUCIDE_UTENSILS "\xee\x8b\xb6"  // U+E2F6
#define ICON_LUCIDE_UTENSILS_CROSSED "\xee\x8b\xb7"  // U+E2F7
#define ICON_LUCIDE_UTILITY_POLE "\xee\x8f\x82"  // U+E3C2
#define ICON_LUCIDE_VAN "\xee\x9a\xad"  // U+E6AD
#define ICON_LUCIDE_VARIABLE "\xee\x91\xb3"  // U+E473
#define ICON_LUCIDE_VAULT "\xee\x96\x8f"  // U+E58F
#define ICON_LUCIDE_VECTOR_SQUARE "\xee\x99\xbc"  // U+E67C
#define ICON_LUCIDE_VEGAN "\xee\x8e\x9d"  // U+E39D
#define ICON_LUCIDE_VENETIAN_MASK "\xee\x8a\xaa"  // U+E2AA
#define ICON_LUCIDE_VENUS "\xee\x99\x85"  // U+E645
#define ICON_LUCIDE_VENUS_AND_MARS "\xee\x99\x86"  // U+E646
#define ICON_LUCIDE_VIBRATE "\xee\x88\xa3"  // U+E223
#define ICON_LUCIDE_VIBRATE_OFF "\xee\x8a\x9d"  // U+E29D
#define ICON_LUCIDE_VIDEO "\xee\x86\xa5"  // U+E1A5
#define ICON_LUCIDE_VIDEO_OFF "\xee\x86\xa6"  // U+E1A6
#define ICON_LUCIDE_VIDEOTAPE "\xee\x93\x8b"  // U+E4CB
#define ICON_LUCIDE_VIEW "\xee\x86\xa7"  // U+E1A7
#define ICON_LUCIDE_VOICEMAIL "\xee\x86\xa8"  // U+E1A8
#define ICON_LUCIDE_VOLLEYBALL "\xee\x98\xaf"  // U+E62F
#define ICON_LUCIDE_VOLUME "\xee\x86\xa9"  // U+E1A9
#define ICON_LUCIDE_VOLUME_1 "\xee\x86\xaa"  // U+E1AA
#define ICON_LUCIDE_VOLUME_2 "\xee\x86\xab"  // U+E1AB
#define ICON_LUCIDE_VOLUME_OFF "\xee\x98\xa6"  // U+E626
#define ICON_LUCIDE_VOLUME_X "\xee\x86\xac"  // U+E1AC
#define ICON_LUCIDE_VOTE "\xee\x8e\xad"  // U+E3AD
#define ICON_LUCIDE_WALLET "\xee\x88\x84"  // U+E204
#define ICON_LUCIDE_WALLET_CARDS "\xee\x93\x8c"  // U+E4CC
#define ICON_LUCIDE_WALLET_MINIMAL "\xee\x93\x8d"  // U+E4CD
#define ICON_LUCIDE_WALLPAPER "\xee\x91\x8b"  // U+E44B
#define ICON_LUCIDE_WAND "\xee\x89\x86"  // U+E246
#define ICON_LUCIDE_WAND_SPARKLES "\xee\x8d\x97"  // U+E357
#define ICON_LUCIDE_WAREHOUSE "\xee\x8f\xa6"  // U+E3E6
#define ICON_LUCIDE_WASHING_MACHINE "\xee\x96\x90"  // U+E590
#define ICON_LUCIDE_WATCH "\xee\x86\xad"  // U+E1AD
#define ICON_LUCIDE_WAVES "\xee\x8a\x83"  // U+E283
#define ICON_LUCIDE_WAVES_ARROW_DOWN "\xee\x9a\xa9"  // U+E6A9
#define ICON_LUCIDE_WAVES_ARROW_UP "\xee\x9a\xaa"  // U+E6AA
#define ICON_LUCIDE_WAVES_LADDER "\xee\x98\xbb"  // U+E63B
#define ICON_LUCIDE_WAYPOINTS "\xee\x95\x82"  // U+E542
#define ICON_LUCIDE_WEBCAM "\xee\x88\x85"  // U+E205
#define ICON_LUCIDE_WEBHOOK "\xee\x8d\xb4"  // U+E374
#define ICON_LUCIDE_WEBHOOK_OFF "\xee\x96\xb7"  // U+E5B7
#define ICON_LUCIDE_WEIGHT "\xee\x94\xb0"  // U+E530
#define ICON_LUCIDE_WEIGHT_TILDE "\xee\x9a\xae"  // U+E6AE
#define ICON_LUCIDE_WHEAT "\xee\x8e\x9e"  // U+E39E
#define ICON_LUCIDE_WHEAT_OFF "\xee\x8e\x9f"  // U+E39F
#define ICON_LUCIDE_WHOLE_WORD "\xee\x8f\x9f"  // U+E3DF
#define ICON_LUCIDE_WIFI "\xee\x86\xae"  // U+E1AE
#define ICON_LUCIDE_WIFI_COG "\xee\x99\xb4"  // U+E674
#define ICON_LUCIDE_WIFI_HIGH "\xee\x97\xb7"  // U+E5F7
#define ICON_LUCIDE_WIFI_LOW "\xee\x97\xb8"  // U+E5F8
#define ICON_LUCIDE_WIFI_OFF "\xee\x86\xaf"  // U+E1AF
#define ICON_LUCIDE_WIFI_PEN "\xee\x99\xa3"  // U+E663
#define ICON_LUCIDE_WIFI_SYNC "\xee\x9a\x81"  // U+E681
#define ICON_LUCIDE_WIFI_ZERO "\xee\x97\xb9"  // U+E5F9
#define ICON_LUCIDE_WIND "\xee\x86\xb0"  // U+E1B0
#define ICON_LUCIDE_WIND_ARROW_DOWN "\xee\x98\xb1"  // U+E631
#define ICON_LUCIDE_WINE "\xee\x8b\xb8"  // U+E2F8
#define ICON_LUCIDE_WINE_OFF "\xee\x8e\xa0"  // U+E3A0
#define ICON_LUCIDE_WORKFLOW "\xee\x90\xa5"  // U+E425
#define ICON_LUCIDE_WORM "\xee\x97\x9a"  // U+E5DA
#define ICON_LUCIDE_WRENCH "\xee\x86\xb1"  // U+E1B1
#define ICON_LUCIDE_X "\xee\x86\xb2"  // U+E1B2
#define ICON_LUCIDE_X_LINE_TOP "\xee\x9b\x8b"  // U+E6CB
#define ICON_LUCIDE_YOUTUBE "\xee\x86\xb3"  // U+E1B3
#define ICON_LUCIDE_ZAP "\xee\x86\xb4"  // U+E1B4
#define ICON_LUCIDE_ZAP_OFF "\xee\x86\xb5"  // U+E1B5
#define ICON_LUCIDE_ZOOM_IN "\xee\x86\xb6"  // U+E1B6
#define ICON_LUCIDE_ZOOM_OUT "\xee\x86\xb7"  // U+E1B7

#endif // LUCIDE_ICONS_H
